# defaults

# Root directory of opensearch distribution
opensearch_location = dist/

# data-node config location
config_location = /etc/graylog/datanode

# locations of opensearch bin, data and log directories 
opensearch_config_location = config
opensearch_data_location = data
opensearch_logs_location = logs

# connection to the mongodb, shared with the Graylog server
mongodb_uri = mongodb://localhost/graylog

# location of the node_id file
node_id_file = data/node-id

# You MUST set a secret to secure/pepper the stored user passwords here. Use at least 64 characters.
# Generate one by using for example: pwgen -N 1 -s 96
# ATTENTION: This value must be the same on all Graylog and Datanode nodes in the cluster.
# Changing this value after installation will render all user sessions and encrypted values in the database invalid. (e.g. encrypted access tokens)
password_secret =

# The default root user is named 'admin'
#root_username = admin

# You MUST specify a hash password for the root user (which you only need to initially set up the
# system and in case you lose connectivity to your authentication backend)
# This password cannot be changed using the API or via the web interface. If you need to change it,
# modify it in this file.
# Create one by using for example: echo -n yourpassword | shasum -a 256
# and put the resulting hash value into the following line
root_password_sha2 =

# Certificate bundles for transport and http layer security. You can generate these using built-in certutil tool
#transport_certificate = datanode-transport-certificates.p12
#transport_certificate_password = password
#http_certificate = datanode-http-certificates.p12
#http_certificate_password = password
