package org.graylog2
 
import org.graylog2.messagehandlers.gelf.GELFMessage;
 
rule "Overwrite localhost host"
	when
		m : GELFMessage( host == "localhost" && version == "2.0" )
	then 
		m.setHost( "localhost.hsoj.org" );
		System.out.println( "[Overwrite localhost rule fired] : " + m.toString() );
end

rule "Drop all messages from www1 facility"
	when
		m : GELFMessage( host == "www1" && facility == "graylog2-test" )
	then
		m.setFilterOut(true);
		System.out.println( "[Drop all messages from www1 facility rule fired] : " + m.toString() );
end

rule "Drop UDP and ICMP Traffic from firewall"
	when
		m : GELFMessage( fullMessage matches "(?i).*(ICMP|UDP)\sPacket(.|\n|\r)*" )
	then
		m.setFilterOut(true);
		System.out.println("[Drop all syslog ICMP and UDP traffic] : " + m.toString() );
end
