import org.graylog2.plugin.logmessage.LogMessage

rule "Rewrite localhost host"
    when
        m : LogMessage( host == "localhost" )
    then 
        m.setHost( "localhost.example.com" );
        System.out.println( "[Overwrite localhost rule fired] : " + m.toString() );
end

rule "Drop UDP and ICMP Traffic from firewall"
    when
        m : LogMessage( fullMessage matches "(?i).*(ICMP|UDP) Packet(.|\n|\r)*" && host == "firewall" )
    then
        m.setFilterOut(true);
        System.out.println("[Drop all syslog ICMP and UDP traffic] : " + m.toString() );
end