import type { DBConnectorGenericInputCreateRequest, DBConnectorInputCreateRequest } from './types';

import type { FormDataType } from '../common/utils/types';

export const toDBConnectorInputCreateRequest = ({
  hostname,
  port,
  databaseName,
  username,
  password,
  dbConnectorName,
  pollingInterval,
  dbType,
  stateFieldType,
  stateField,
  tableName,
  enableThrottling,
  mongoCollectionName,
  overrideSource,
}: FormDataType): DBConnectorInputCreateRequest => ({
  name: dbConnectorName.value,
  hostname:hostname.value,
  port:port.value,
  database_name:databaseName.value,
  username:username.value,
  password:password.value,
  db_type:dbType.value,
  polling_interval: pollingInterval.value,
  polling_time_unit: 'MINUTES',
  state_field_type: stateFieldType.value,
  state_field: stateField.value,
  table_name: tableName.value,
  enable_throttling: !!enableThrottling.value,
  mongo_collection_name: mongoCollectionName.value,
  override_source: overrideSource?.value,
});

export const toGenericInputCreateRequest = ({
  hostname,
  port,
  databaseName,
  username,
  password,
  dbConnectorName,
  dbType,
  pollingInterval,
  mongoCollectionName,
  stateFieldType,
  stateField,
  tableName,
  enableThrottling,
  overrideSource,
}: FormDataType): DBConnectorGenericInputCreateRequest => ({
  type: 'org.graylog.integrations.dbconnector.DBConnectorInput',
  title: dbConnectorName.value,
  global: false,
  configuration: {
    hostname:hostname.value,
    port:port.value,
    database_name:databaseName.value,
    username:username.value,
    password:password.value,
    mongo_collection_name: mongoCollectionName.value,
    db_type:dbType.value,
    polling_interval: pollingInterval.value,
    polling_time_unit: 'MINUTES',
    state_field_type: stateFieldType.value,
    state_field: stateField.value,
    table_name: tableName.value,
    throttling_allowed: !!enableThrottling?.value,
    override_source: overrideSource?.value,

  },
});