export type DBConnectorGenericInputCreateRequest = {
  type: 'org.graylog.integrations.dbconnector.DBConnectorInput',
  title: string,
  global: boolean,
  configuration: {
    db_type: string,
    polling_interval: number,
    polling_time_unit: 'MILLISECONDS' | 'MICROSECONDS' | 'HOURS' | 'SECONDS' | 'NANOSECONDS' | 'DAYS' | 'MINUTES',
    hostname: string,
    port: number,
    database_name: string,
    username: string,
    password: string,
    state_field_type: string,
    state_field: string,
    table_name: String,
    throttling_allowed: boolean,
    mongo_collection_name: string,
    override_source: string,
  },
};

export type DBConnectorInputCreateRequest = {
  name: string,
  db_type: string,
  polling_interval: number,
  polling_time_unit: 'MILLISECONDS' | 'MICROSECONDS' | 'HOURS' | 'SECONDS' | 'NANOSECONDS' | 'DAYS' | 'MINUTES',
  hostname: string,
  port: number,
  database_name: string,
  username: string,
  password: string,
  state_field_type: string,
  state_field: string,
  table_name: string,
  enable_throttling: boolean,
  mongo_collection_name: string,
  override_source: string,

};
