type = "f"
message = "Fix event definition jobs to unlock after a server crashed."
message = "Unlock event definition jobs after a server crash to make sure they continue to execute."

issues = ["8612"]
pulls = ["11249"]
