type = "c"
message = "Prevent messages from being ingested with timestamps that are in the future. Invalid timestamps will be forced to the receive time or current time."

pulls = ["21429"]
issues = ["21408"]
