--- Graylog2 REST API ---
---
Welcome to the REST API documentation of Graylog2 **v0.20.0-dev**. This API is still in draft mode until the first stable release, planned for the end of this summer.

You can append a `pretty=true` GET parameter to every call to get a pretty-printed and formatted JSON result.
---


--
Messages
Resources mostly related to single messages identified by an ID.
--

Get a single message in detail. Note the index specified as URL parameter. (for example: graylog2_38)
The index a message is stored in is included in every search result.
GET /messages/{index}/{message_id}
< 200
< Content-Type: application/json
{
  "message" : {
    "message" : "sundaysister kernel[0]: AirPort: Link Up on en0\n",
    "timestamp" : "2013-07-15 02-36-34.000",
    "level" : 7,
    "source" : "sundaysister",
    "facility" : "kernel",
    "_id" : "9a3eb412-ece6-11e2-a7d5-4c8d79f2b596",
    "full_message" : "<7>Jul 15 02:36:34 sundaysister kernel[0]: AirPort: Link Up on en0\n",
    "streams" : [ ]
  },
  "index" : "graylog2_38"
}

Analyze a string included in a message. Gives back the tokens this string was broken into.
GET /messages/{index}/analyze{?string}
< 200
< Content-Type: application/json
{
  "tokens" : [ "sundaysister", "kernel", "0", "airport", "link", "up", "en0", "n" ]
}

--
Message counts
Resources related to message counts.
--

Get the total number of messages in your Graylog2 setup.
GET /count/total
< 200
< Content-Type: application/json
{
    "events":55318286
}

Get a histogram of message counts for a specified timerange in a specified interval.

  * **interval**: One of year, quarter, month, week, day, hour or minute (controls bucket sizes)
  * **timerange**: From how many seconds in the past to start. Example: 300 means last 5 minutes.
GET /count/histogram{?interval,timerange}
< 200
< Content-Type: application/json
{
    "time":35,
    "results": {
        "1373846400":113,
        "1373850000":192,
        "1373853600":281
    },
    "interval":"hour",
    "query":"match_all"
}

--
Cluster
Resources related to your graylog2-server cluster.
--

Get a list of all active graylog2-server nodes.
GET /cluster/nodes
< 200
< Content-Type: application/json
{
    "total":2,
    "nodes": [
        {
            "hostname":"localhost",
            "last_seen":"2013-07-17T22:41:21.000+02:00",
            "transport_address":"http://127.0.0.1:12900/",
            "node_id":"localhost-c65f4556-798c-4507-a258-422a4dda330e"
        },
        {
            "hostname":"localhost",
            "last_seen":"2013-07-17T22:41:21.000+02:00",
            "transport_address":"http://127.0.0.1:12910/",
            "node_id":"localhost-b1772993-3445-4c74-9268-9dbb773b4b02"
        }
    ]
}

Get information of a single graylog2-server node.
GET /cluster/nodes/{node_id}
< 200
< Content-Type: application/json
{
    "hostname":"localhost",
    "last_seen":"2013-07-17T23:03:56.000+02:00",
    "transport_address":"http://127.0.0.1:12900/",
    "node_id":"localhost-c65f4556-798c-4507-a258-422a4dda330e"
}