--- Graylog2 REST API ---
---
Welcome to the REST API documentation of Graylog2 **v0.20.0-dev**. This API is still in draft mode until the first stable release, planned for the end of this summer.
---


--
Cluster
Resources related to your graylog2-server cluster.
--

Get a list of all active nodes.
GET /cluster/nodes
< 200
< Content-Type: application/json
{"total":2,"nodes":[{"hostname":"localhost","last_seen":"2013-07-17T22:41:21.000+02:00","transport_address":"http://127.0.0.1:12900/","node_id":"localhost-c65f4556-798c-4507-a258-422a4dda330e"},{"hostname":"localhost","last_seen":"2013-07-17T22:41:21.000+02:00","transport_address":"http://127.0.0.1:12910/","node_id":"localhost-b1772993-3445-4c74-9268-9dbb773b4b02"}]}
