const LOGIN_INITIALIZING_STATE = 'INITIALIZING';
const LOGIN_INITIALIZED_STATE = 'INITIALIZED';
const LOGIN_TRANSITIONING_STATE = 'TRANSITIONING';

export {
  LOGIN_INITIALIZING_STATE,
  LOGIN_INITIALIZED_STATE,
  LOGIN_TRANSITIONING_STATE,
};
