---
##
# Copyright OpenSearch Contributors
# SPDX-License-Identifier: Apache-2.0
##

# configuration file for the observability plugin
opensearch.notebooks:
  general:
    operationTimeoutMs: 60000 # 60 seconds, Minimum 100ms
    defaultItemsQueryCount: 100 # default number of items to query
  polling:
    jobLockDurationSeconds: 300 # 5 Minutes, Minimum 10 seconds
    minPollingDurationSeconds: 300 # 5 Minutes, Minimum 60 seconds
    maxPollingDurationSeconds: 900 # 15 Minutes, Minimum 5 Minutes
    maxLockRetries: 1 # Max number of retries to retry locking
  access:
    adminAccess: "AllObservabilityObjects"
    # adminAccess values:
    ## Standard -> Admin user access follows standard user
    ## AllObservabilityObjects -> Admin user with "all_access" role can see all observability objects of all users.
    filterBy: "NoFilter" # Applied when tenant != __user__
    # filterBy values:
    ## NoFilter -> everyone see each other's observability objects
    ## User -> observability objects are visible to only themselves
    ## Roles -> observability objects are visible to users having any one of the role of creator
    ## BackendRoles -> observability objects are visible to users having any one of the backend role of creator
    ignoreRoles: ["own_index", "kibana_user", "observability_full_access", "observability_read_access"]
