/*
 * Copyright (C) 2020 Graylog, Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the Server Side Public License, version 1,
 * as published by MongoDB, Inc.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Server Side Public License for more details.
 *
 * You should have received a copy of the Server Side Public License
 * along with this program. If not, see
 * <http://www.mongodb.com/licensing/server-side-public-license>.
 */
package org.graylog2.rest.resources.system;

import com.codahale.metrics.annotation.Timed;
import com.mongodb.client.model.Filters;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.parameters.RequestBody;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.inject.Inject;
import jakarta.inject.Named;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import jakarta.ws.rs.BadRequestException;
import jakarta.ws.rs.Consumes;
import jakarta.ws.rs.DELETE;
import jakarta.ws.rs.DefaultValue;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.PUT;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.PathParam;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.QueryParam;
import jakarta.ws.rs.core.Context;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;
import org.apache.shiro.authz.annotation.RequiresAuthentication;
import org.apache.shiro.authz.annotation.RequiresPermissions;
import org.bson.conversions.Bson;
import org.graylog.events.processor.systemnotification.SystemNotificationRenderService;
import org.graylog.events.processor.systemnotification.TemplateRenderResponse;
import org.graylog.security.UserContext;
import org.graylog2.audit.AuditEventTypes;
import org.graylog2.audit.jersey.AuditEvent;
import org.graylog2.audit.jersey.NoAuditEvent;
import org.graylog2.database.filtering.ComputedFieldRegistry;
import org.graylog2.database.filtering.DbQueryCreator;
import org.graylog2.notifications.Notification;
import org.graylog2.notifications.NotificationService;
import org.graylog2.notifications.SystemNotificationDto;
import org.graylog2.notifications.SystemNotificationRetentionConfig;
import org.graylog2.notifications.SystemNotificationService;
import org.graylog2.plugin.cluster.ClusterConfigService;
import org.graylog2.rest.bulk.model.BulkOperationRequest;
import org.graylog2.rest.models.SortOrder;
import org.graylog2.rest.models.tools.responses.PageListResponse;
import org.graylog2.rest.resources.entities.EntityAttribute;
import org.graylog2.rest.resources.entities.EntityDefaults;
import org.graylog2.rest.resources.entities.FilterOption;
import org.graylog2.rest.resources.entities.Sorting;
import org.graylog2.search.SearchQueryField;
import org.graylog2.shared.rest.PublicCloudAPI;
import org.graylog2.shared.rest.resources.RestResource;
import org.graylog2.shared.security.RestPermissions;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.annotation.Nullable;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

import static org.graylog2.shared.utilities.StringUtils.f;

@RequiresAuthentication
@PublicCloudAPI
@Tag(name = "System/Notifications", description = "Notifications generated by the system")
@Path("/system/notifications")
public class NotificationsResource extends RestResource {

    private static final Logger LOG = LoggerFactory.getLogger(NotificationsResource.class);

    private static final List<EntityAttribute> ATTRIBUTES = List.of(
            EntityAttribute.builder().id(SystemNotificationDto.FIELD_TITLE).title("Title")
                    .type(SearchQueryField.Type.STRING).sortable(true).searchable(true).build(),
            EntityAttribute.builder().id(SystemNotificationDto.FIELD_DESCRIPTION).title("Description")
                    .type(SearchQueryField.Type.STRING).sortable(false).searchable(true).hidden(true).build(),
            EntityAttribute.builder().id(SystemNotificationDto.FIELD_TYPE).title("Type")
                    .type(SearchQueryField.Type.STRING).sortable(true).filterable(true).searchable(true).build(),
            EntityAttribute.builder().id(SystemNotificationDto.FIELD_SEVERITY).title("Severity")
                    .type(SearchQueryField.Type.STRING).sortable(true).filterable(true)
                    .filterOptions(Set.of(
                            FilterOption.create("normal", "Normal"),
                            FilterOption.create("urgent", "Urgent")
                    )).build(),
            EntityAttribute.builder().id(SystemNotificationDto.FIELD_IS_READ).title("Read")
                    .type(SearchQueryField.Type.BOOLEAN).sortable(true).filterable(true)
                    .filterOptions(Set.of(
                            FilterOption.create("true", "Read"),
                            FilterOption.create("false", "Unread")
                    )).build(),
            EntityAttribute.builder().id("actor.id").title("Actor ID").dbField("actor.id")
                    .type(SearchQueryField.Type.STRING).sortable(false).hidden(true).build(),
            EntityAttribute.builder().id("actor.name").title("Actor").dbField("actor.name")
                    .type(SearchQueryField.Type.STRING).sortable(true).build(),
            EntityAttribute.builder().id(SystemNotificationDto.FIELD_TRIGGERED_AT).title("Triggered")
                    .type(SearchQueryField.Type.DATE).sortable(true).build(),
            EntityAttribute.builder().id(SystemNotificationDto.FIELD_LAST_CHANGED).title("Last changed")
                    .type(SearchQueryField.Type.DATE).sortable(true).hidden(true).build()
    );

    private static final EntityDefaults DEFAULTS = EntityDefaults.builder()
            .sort(Sorting.create(SystemNotificationDto.FIELD_TRIGGERED_AT, Sorting.Direction.DESC))
            .build();

    private final NotificationService notificationService;
    private final SystemNotificationService systemNotificationService;
    private final SystemNotificationRenderService renderService;
    private final ClusterConfigService clusterConfigService;
    private final DbQueryCreator dbQueryCreator;
    private final boolean isCloud;

    @Inject
    public NotificationsResource(NotificationService notificationService,
                                 SystemNotificationService systemNotificationService,
                                 SystemNotificationRenderService renderService,
                                 ClusterConfigService clusterConfigService,
                                 ComputedFieldRegistry computedFieldRegistry,
                                 @Named("is_cloud") boolean isCloud) {
        this.notificationService = notificationService;
        this.systemNotificationService = systemNotificationService;
        this.renderService = renderService;
        this.clusterConfigService = clusterConfigService;
        this.dbQueryCreator = new DbQueryCreator(SystemNotificationDto.FIELD_TITLE, ATTRIBUTES, computedFieldRegistry);
        this.isCloud = isCloud;
    }

    // ---- Legacy endpoints (backward compat) ----

    public record NotificationsResponse(int total, List<Notification> notifications) {
        static NotificationsResponse create(List<Notification> notifications) {
            return new NotificationsResponse(notifications.size(), notifications);
        }
    }

    @GET
    @Timed
    @Operation(summary = "Get all active notifications")
    @Produces(MediaType.APPLICATION_JSON)
    public NotificationsResponse listNotifications() {
        final var notifications = notificationService.all().stream()
                .filter(notification -> !isCloud || !Notification.CLOUD_SUPPRESSED_TYPES.contains(notification.getType()))
                .filter(notification -> isPermitted(RestPermissions.NOTIFICATIONS_READ, notification.getType().toString()))
                .toList();

        return NotificationsResponse.create(notifications);
    }

    @DELETE
    @Timed
    @Path("/{notificationType}")
    @Operation(summary = "Delete a notification by type")
    @Produces(MediaType.APPLICATION_JSON)
    @ApiResponses(value = {
            @ApiResponse(responseCode = "204", description = "Success"),
            @ApiResponse(responseCode = "404", description = "No such notification type.")
    })
    @AuditEvent(type = AuditEventTypes.SYSTEM_NOTIFICATION_UPDATE)
    public void deleteNotification(@Parameter(name = "notificationType")
                                   @PathParam("notificationType") String notificationType) {
        deleteKeyedNotification(notificationType, null);
    }

    @DELETE
    @Timed
    @Path("/{notificationType}/{notificationKey}")
    @Operation(summary = "Delete a notification by type and key")
    @Produces(MediaType.APPLICATION_JSON)
    @ApiResponses(value = {
            @ApiResponse(responseCode = "204", description = "Success"),
            @ApiResponse(responseCode = "404", description = "No such notification type.")
    })
    @AuditEvent(type = AuditEventTypes.SYSTEM_NOTIFICATION_UPDATE)
    public void deleteKeyedNotification(@Parameter(name = "notificationType") @PathParam("notificationType") String notificationType,
                                        @Parameter(name = "notificationKey") @PathParam("notificationKey") @Nullable String notificationKey) {
        Notification.Type type;
        checkPermission(RestPermissions.NOTIFICATIONS_DELETE, notificationType);
        try {
            type = Notification.Type.valueOf(notificationType.toUpperCase(Locale.ENGLISH));
        } catch (IllegalArgumentException e) {
            LOG.warn("No such notification type: [" + notificationType + "]");
            throw new BadRequestException(e);
        }

        notificationService.destroyAllByTypeAndKey(type, notificationKey);
    }

    // ---- New paginated entity table endpoints ----

    @GET
    @Timed
    @Path("/paginated")
    @Operation(summary = "Get paginated system notifications")
    @Produces(MediaType.APPLICATION_JSON)
    @NoAuditEvent("Read-only endpoint")
    public PageListResponse<SystemNotificationDto> getPaginated(
            @QueryParam("page") @DefaultValue("1") int page,
            @QueryParam("per_page") @DefaultValue("50") int perPage,
            @QueryParam("query") @DefaultValue("") String query,
            @QueryParam("filters") List<String> filters,
            @QueryParam("sort") @DefaultValue(SystemNotificationDto.FIELD_TRIGGERED_AT) String sortField,
            @QueryParam("order") @DefaultValue("desc") SortOrder order) {
        checkPermission(RestPermissions.NOTIFICATIONS_READ);

        final Bson dbQuery = buildPaginatedQuery(filters, query);
        final Bson sort = order.toBsonSort(sortField);

        final var result = systemNotificationService.searchPaginated(dbQuery, sort, page, perPage);

        return PageListResponse.create(
                query,
                result.pagination(),
                result.pagination().total(),
                sortField,
                order,
                result,
                ATTRIBUTES,
                DEFAULTS
        );
    }

    @GET
    @Timed
    @Path("/unread/count")
    @Operation(summary = "Get the count of unread system notifications")
    @Produces(MediaType.APPLICATION_JSON)
    @NoAuditEvent("Read-only endpoint")
    public long getUnreadCount() {
        checkPermission(RestPermissions.NOTIFICATIONS_READ);
        return systemNotificationService.countUnread();
    }

    @PUT
    @Timed
    @Path("/{id}/toggle_read")
    @Operation(summary = "Toggle a notification's read state")
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_JSON)
    @AuditEvent(type = AuditEventTypes.SYSTEM_NOTIFICATION_UPDATE)
    public SystemNotificationDto toggleRead(@Parameter(name = "id") @PathParam("id") String id,
                                            @Context UserContext userContext) {
        checkPermission(RestPermissions.NOTIFICATIONS_READ);

        final SystemNotificationDto dto = systemNotificationService.findById(id)
                .orElseThrow(() -> new jakarta.ws.rs.NotFoundException(f("Notification <%s> not found", id)));

        final var actor = SystemNotificationDto.Actor.create(
                userContext.getUserId(),
                userContext.getUser().getFullName()
        );

        if (dto.isRead()) {
            systemNotificationService.markAsUnread(List.of(id), actor);
        } else {
            systemNotificationService.markAsRead(List.of(id), actor);
        }

        return systemNotificationService.findById(id).orElseThrow();
    }

    @POST
    @Timed
    @Path("/bulk/toggle_read")
    @Operation(summary = "Toggle the read state of selected notifications")
    @Consumes(MediaType.APPLICATION_JSON)
    @AuditEvent(type = AuditEventTypes.SYSTEM_NOTIFICATION_UPDATE)
    public Response bulkToggleRead(@Valid @NotNull BulkOperationRequest request,
                                   @Context UserContext userContext) {
        checkPermission(RestPermissions.NOTIFICATIONS_READ);

        final var actor = SystemNotificationDto.Actor.create(
                userContext.getUserId(),
                userContext.getUser().getFullName()
        );

        systemNotificationService.toggleReadState(request.entityIds(), actor);
        return Response.noContent().build();
    }

    @POST
    @Timed
    @Path("/bulk/read_all")
    @Operation(summary = "Mark all notifications as read")
    @Consumes(MediaType.APPLICATION_JSON)
    @AuditEvent(type = AuditEventTypes.SYSTEM_NOTIFICATION_UPDATE)
    public Response readAll(@Context UserContext userContext) {
        checkPermission(RestPermissions.NOTIFICATIONS_READ);

        final var actor = SystemNotificationDto.Actor.create(
                userContext.getUserId(),
                userContext.getUser().getFullName()
        );

        systemNotificationService.markAllAsRead(actor);
        return Response.noContent().build();
    }

    // ---- HTML render endpoint ----

    @GET
    @Timed
    @Path("/{id}/message/html")
    @Operation(summary = "Render the HTML message for a notification by ID")
    @Produces(MediaType.APPLICATION_JSON)
    @NoAuditEvent("Read-only endpoint")
    public TemplateRenderResponse renderHtmlById(@Parameter(name = "id") @PathParam("id") String id) {
        checkPermission(RestPermissions.NOTIFICATIONS_READ);

        final SystemNotificationDto dto = systemNotificationService.findById(id)
                .orElseThrow(() -> new jakarta.ws.rs.NotFoundException(f("Notification <%s> not found", id)));

        final Notification.Type type;
        try {
            type = Notification.Type.valueOf(dto.type().toUpperCase(Locale.ENGLISH));
        } catch (IllegalArgumentException e) {
            throw new BadRequestException(f("Unknown notification type: %s", dto.type()));
        }

        final Map<String, Object> values = new HashMap<>();
        if (dto.details() != null) {
            values.putAll(dto.details());
        }

        final var rendered = renderService.render(
                new org.graylog2.notifications.NotificationView(dto),
                SystemNotificationRenderService.Format.HTML,
                values
        );

        return TemplateRenderResponse.create(rendered.title, rendered.description);
    }

    // ---- Retention config endpoints ----

    @GET
    @Timed
    @Path("/config")
    @Operation(summary = "Get the notification retention configuration")
    @Produces(MediaType.APPLICATION_JSON)
    @RequiresPermissions(RestPermissions.NOTIFICATIONS_CONFIG_READ)
    @NoAuditEvent("Read-only endpoint")
    public SystemNotificationRetentionConfig getConfig() {
        return clusterConfigService.getOrDefault(
                SystemNotificationRetentionConfig.class,
                SystemNotificationRetentionConfig.createDefault()
        );
    }

    @PUT
    @Timed
    @Path("/config")
    @Operation(summary = "Update the notification retention configuration")
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_JSON)
    @RequiresPermissions(RestPermissions.NOTIFICATIONS_CONFIG_UPDATE)
    @AuditEvent(type = AuditEventTypes.CLUSTER_CONFIGURATION_UPDATE)
    public SystemNotificationRetentionConfig updateConfig(@Valid @NotNull @RequestBody(required = true, useParameterTypeSchema = true) SystemNotificationRetentionConfig config) {
        if (config.retentionDays() <= 0) {
            throw new BadRequestException("retention_days must be a positive integer");
        }
        clusterConfigService.write(config);
        return config;
    }

    // ---- Private helpers ----

    private Bson buildPaginatedQuery(List<String> filters, String query) {
        final Bson baseQuery = dbQueryCreator.createDbQuery(filters, query);

        if (isCloud) {
            // Suppress cloud-excluded notification types
            final List<String> suppressedTypes = Notification.CLOUD_SUPPRESSED_TYPES.stream()
                    .map(t -> t.toString().toLowerCase(Locale.ENGLISH))
                    .toList();
            return Filters.and(baseQuery, Filters.nin(SystemNotificationDto.FIELD_TYPE, suppressedTypes));
        }

        return baseQuery;
    }
}
