// flow-typed signature: de1af41d5a17b09e57abe039343f5783
// flow-typed version: <<STUB>>/crossfilter_v1.3.12/flow_v0.117.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'crossfilter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'crossfilter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'crossfilter/crossfilter' {
  declare module.exports: any;
}

declare module 'crossfilter/crossfilter.min' {
  declare module.exports: any;
}

declare module 'crossfilter/src/array' {
  declare module.exports: any;
}

declare module 'crossfilter/src/bisect' {
  declare module.exports: any;
}

declare module 'crossfilter/src/crossfilter' {
  declare module.exports: any;
}

declare module 'crossfilter/src/filter' {
  declare module.exports: any;
}

declare module 'crossfilter/src/heap' {
  declare module.exports: any;
}

declare module 'crossfilter/src/heapselect' {
  declare module.exports: any;
}

declare module 'crossfilter/src/identity' {
  declare module.exports: any;
}

declare module 'crossfilter/src/insertionsort' {
  declare module.exports: any;
}

declare module 'crossfilter/src/null' {
  declare module.exports: any;
}

declare module 'crossfilter/src/permute' {
  declare module.exports: any;
}

declare module 'crossfilter/src/quicksort' {
  declare module.exports: any;
}

declare module 'crossfilter/src/reduce' {
  declare module.exports: any;
}

declare module 'crossfilter/src/zero' {
  declare module.exports: any;
}

// Filename aliases
declare module 'crossfilter/crossfilter.js' {
  declare module.exports: $Exports<'crossfilter/crossfilter'>;
}
declare module 'crossfilter/crossfilter.min.js' {
  declare module.exports: $Exports<'crossfilter/crossfilter.min'>;
}
declare module 'crossfilter/index' {
  declare module.exports: $Exports<'crossfilter'>;
}
declare module 'crossfilter/index.js' {
  declare module.exports: $Exports<'crossfilter'>;
}
declare module 'crossfilter/src/array.js' {
  declare module.exports: $Exports<'crossfilter/src/array'>;
}
declare module 'crossfilter/src/bisect.js' {
  declare module.exports: $Exports<'crossfilter/src/bisect'>;
}
declare module 'crossfilter/src/crossfilter.js' {
  declare module.exports: $Exports<'crossfilter/src/crossfilter'>;
}
declare module 'crossfilter/src/filter.js' {
  declare module.exports: $Exports<'crossfilter/src/filter'>;
}
declare module 'crossfilter/src/heap.js' {
  declare module.exports: $Exports<'crossfilter/src/heap'>;
}
declare module 'crossfilter/src/heapselect.js' {
  declare module.exports: $Exports<'crossfilter/src/heapselect'>;
}
declare module 'crossfilter/src/identity.js' {
  declare module.exports: $Exports<'crossfilter/src/identity'>;
}
declare module 'crossfilter/src/insertionsort.js' {
  declare module.exports: $Exports<'crossfilter/src/insertionsort'>;
}
declare module 'crossfilter/src/null.js' {
  declare module.exports: $Exports<'crossfilter/src/null'>;
}
declare module 'crossfilter/src/permute.js' {
  declare module.exports: $Exports<'crossfilter/src/permute'>;
}
declare module 'crossfilter/src/quicksort.js' {
  declare module.exports: $Exports<'crossfilter/src/quicksort'>;
}
declare module 'crossfilter/src/reduce.js' {
  declare module.exports: $Exports<'crossfilter/src/reduce'>;
}
declare module 'crossfilter/src/zero.js' {
  declare module.exports: $Exports<'crossfilter/src/zero'>;
}
