// flow-typed signature: 5540993b7be8438c22a9aace67954154
// flow-typed version: <<STUB>>/graylog-web-plugin_vfile:../../graylog2-server/graylog2-web-interface/packages/graylog-web-plugin/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graylog-web-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graylog-web-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graylog-web-plugin/lib/loadBuildConfig' {
  declare module.exports: any;
}

declare module 'graylog-web-plugin/lib/PluginManifest' {
  declare module.exports: any;
}

declare module 'graylog-web-plugin/lib/PluginStore' {
  declare module.exports: any;
}

declare module 'graylog-web-plugin/lib/PluginWebpackConfig' {
  declare module.exports: any;
}

declare module 'graylog-web-plugin/plugin' {
  declare module.exports: any;
}

declare module 'graylog-web-plugin/src/loadBuildConfig' {
  declare module.exports: any;
}

declare module 'graylog-web-plugin/src/PluginManifest' {
  declare module.exports: any;
}

declare module 'graylog-web-plugin/src/PluginStore' {
  declare module.exports: any;
}

declare module 'graylog-web-plugin/src/PluginWebpackConfig' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graylog-web-plugin/index' {
  declare module.exports: $Exports<'graylog-web-plugin'>;
}
declare module 'graylog-web-plugin/index.js' {
  declare module.exports: $Exports<'graylog-web-plugin'>;
}
declare module 'graylog-web-plugin/lib/loadBuildConfig.js' {
  declare module.exports: $Exports<'graylog-web-plugin/lib/loadBuildConfig'>;
}
declare module 'graylog-web-plugin/lib/PluginManifest.js' {
  declare module.exports: $Exports<'graylog-web-plugin/lib/PluginManifest'>;
}
declare module 'graylog-web-plugin/lib/PluginStore.js' {
  declare module.exports: $Exports<'graylog-web-plugin/lib/PluginStore'>;
}
declare module 'graylog-web-plugin/lib/PluginWebpackConfig.js' {
  declare module.exports: $Exports<'graylog-web-plugin/lib/PluginWebpackConfig'>;
}
declare module 'graylog-web-plugin/plugin.js' {
  declare module.exports: $Exports<'graylog-web-plugin/plugin'>;
}
declare module 'graylog-web-plugin/src/loadBuildConfig.js' {
  declare module.exports: $Exports<'graylog-web-plugin/src/loadBuildConfig'>;
}
declare module 'graylog-web-plugin/src/PluginManifest.js' {
  declare module.exports: $Exports<'graylog-web-plugin/src/PluginManifest'>;
}
declare module 'graylog-web-plugin/src/PluginStore.jsx' {
  declare module.exports: $Exports<'graylog-web-plugin/src/PluginStore'>;
}
declare module 'graylog-web-plugin/src/PluginWebpackConfig.js' {
  declare module.exports: $Exports<'graylog-web-plugin/src/PluginWebpackConfig'>;
}
