// flow-typed signature: fc51b7fa2a2f0eeb24d76de621fcc9c9
// flow-typed version: <<STUB>>/react-bootstrap_v0.31.5/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-bootstrap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-bootstrap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-bootstrap/dist/react-bootstrap' {
  declare module.exports: any;
}

declare module 'react-bootstrap/dist/react-bootstrap.min' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Accordion' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Alert' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Badge' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Breadcrumb' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/BreadcrumbItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Button' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ButtonGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ButtonToolbar' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Carousel' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/CarouselCaption' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/CarouselItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Checkbox' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Clearfix' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/CloseButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Col' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Collapse' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ControlLabel' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Dropdown' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/DropdownButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/DropdownMenu' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/DropdownToggle' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Fade' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Form' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/FormControl' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/FormControlFeedback' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/FormControlStatic' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/FormGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Glyphicon' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Grid' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/HelpBlock' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Image' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/index' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/InputGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/InputGroupAddon' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/InputGroupButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Jumbotron' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Label' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ListGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ListGroupItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Media' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/MediaBody' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/MediaHeading' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/MediaLeft' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/MediaList' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/MediaListItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/MediaRight' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/MenuItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Modal' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ModalBody' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ModalDialog' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ModalFooter' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ModalHeader' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ModalTitle' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Nav' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Navbar' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/NavbarBrand' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/NavbarCollapse' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/NavbarHeader' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/NavbarToggle' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/NavDropdown' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/NavItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Overlay' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/OverlayTrigger' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/PageHeader' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/PageItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Pager' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/PagerItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Pagination' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/PaginationButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Panel' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/PanelGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Popover' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ProgressBar' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Radio' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ResponsiveEmbed' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Row' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/SafeAnchor' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/SplitButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/SplitToggle' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Tab' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/TabContainer' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/TabContent' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Table' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/TabPane' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Tabs' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Thumbnail' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ToggleButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/ToggleButtonGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Tooltip' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/utils/bootstrapUtils' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/utils/capitalize' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/utils/createChainedFunction' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/utils/deprecationWarning' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/utils/index' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/utils/PropTypes' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/utils/splitComponentProps' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/utils/StyleConfig' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/utils/TransitionEvents' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/utils/ValidComponentChildren' {
  declare module.exports: any;
}

declare module 'react-bootstrap/es/Well' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Accordion' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Alert' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Badge' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Breadcrumb' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/BreadcrumbItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Button' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ButtonGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ButtonToolbar' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Carousel' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/CarouselCaption' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/CarouselItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Checkbox' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Clearfix' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/CloseButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Col' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Collapse' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ControlLabel' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Dropdown' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/DropdownButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/DropdownMenu' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/DropdownToggle' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Fade' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Form' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/FormControl' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/FormControlFeedback' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/FormControlStatic' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/FormGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Glyphicon' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Grid' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/HelpBlock' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Image' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/index' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/InputGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/InputGroupAddon' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/InputGroupButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Jumbotron' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Label' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ListGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ListGroupItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Media' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/MediaBody' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/MediaHeading' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/MediaLeft' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/MediaList' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/MediaListItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/MediaRight' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/MenuItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Modal' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ModalBody' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ModalDialog' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ModalFooter' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ModalHeader' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ModalTitle' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Nav' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Navbar' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/NavbarBrand' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/NavbarCollapse' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/NavbarHeader' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/NavbarToggle' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/NavDropdown' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/NavItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Overlay' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/OverlayTrigger' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/PageHeader' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/PageItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Pager' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/PagerItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Pagination' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/PaginationButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Panel' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/PanelGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Popover' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ProgressBar' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Radio' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ResponsiveEmbed' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Row' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/SafeAnchor' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/SplitButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/SplitToggle' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Tab' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/TabContainer' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/TabContent' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Table' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/TabPane' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Tabs' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Thumbnail' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ToggleButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/ToggleButtonGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Tooltip' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/utils/bootstrapUtils' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/utils/capitalize' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/utils/createChainedFunction' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/utils/deprecationWarning' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/utils/index' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/utils/PropTypes' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/utils/splitComponentProps' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/utils/StyleConfig' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/utils/TransitionEvents' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/utils/ValidComponentChildren' {
  declare module.exports: any;
}

declare module 'react-bootstrap/lib/Well' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-bootstrap/dist/react-bootstrap.js' {
  declare module.exports: $Exports<'react-bootstrap/dist/react-bootstrap'>;
}
declare module 'react-bootstrap/dist/react-bootstrap.min.js' {
  declare module.exports: $Exports<'react-bootstrap/dist/react-bootstrap.min'>;
}
declare module 'react-bootstrap/es/Accordion.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Accordion'>;
}
declare module 'react-bootstrap/es/Alert.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Alert'>;
}
declare module 'react-bootstrap/es/Badge.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Badge'>;
}
declare module 'react-bootstrap/es/Breadcrumb.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Breadcrumb'>;
}
declare module 'react-bootstrap/es/BreadcrumbItem.js' {
  declare module.exports: $Exports<'react-bootstrap/es/BreadcrumbItem'>;
}
declare module 'react-bootstrap/es/Button.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Button'>;
}
declare module 'react-bootstrap/es/ButtonGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ButtonGroup'>;
}
declare module 'react-bootstrap/es/ButtonToolbar.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ButtonToolbar'>;
}
declare module 'react-bootstrap/es/Carousel.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Carousel'>;
}
declare module 'react-bootstrap/es/CarouselCaption.js' {
  declare module.exports: $Exports<'react-bootstrap/es/CarouselCaption'>;
}
declare module 'react-bootstrap/es/CarouselItem.js' {
  declare module.exports: $Exports<'react-bootstrap/es/CarouselItem'>;
}
declare module 'react-bootstrap/es/Checkbox.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Checkbox'>;
}
declare module 'react-bootstrap/es/Clearfix.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Clearfix'>;
}
declare module 'react-bootstrap/es/CloseButton.js' {
  declare module.exports: $Exports<'react-bootstrap/es/CloseButton'>;
}
declare module 'react-bootstrap/es/Col.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Col'>;
}
declare module 'react-bootstrap/es/Collapse.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Collapse'>;
}
declare module 'react-bootstrap/es/ControlLabel.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ControlLabel'>;
}
declare module 'react-bootstrap/es/Dropdown.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Dropdown'>;
}
declare module 'react-bootstrap/es/DropdownButton.js' {
  declare module.exports: $Exports<'react-bootstrap/es/DropdownButton'>;
}
declare module 'react-bootstrap/es/DropdownMenu.js' {
  declare module.exports: $Exports<'react-bootstrap/es/DropdownMenu'>;
}
declare module 'react-bootstrap/es/DropdownToggle.js' {
  declare module.exports: $Exports<'react-bootstrap/es/DropdownToggle'>;
}
declare module 'react-bootstrap/es/Fade.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Fade'>;
}
declare module 'react-bootstrap/es/Form.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Form'>;
}
declare module 'react-bootstrap/es/FormControl.js' {
  declare module.exports: $Exports<'react-bootstrap/es/FormControl'>;
}
declare module 'react-bootstrap/es/FormControlFeedback.js' {
  declare module.exports: $Exports<'react-bootstrap/es/FormControlFeedback'>;
}
declare module 'react-bootstrap/es/FormControlStatic.js' {
  declare module.exports: $Exports<'react-bootstrap/es/FormControlStatic'>;
}
declare module 'react-bootstrap/es/FormGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/es/FormGroup'>;
}
declare module 'react-bootstrap/es/Glyphicon.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Glyphicon'>;
}
declare module 'react-bootstrap/es/Grid.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Grid'>;
}
declare module 'react-bootstrap/es/HelpBlock.js' {
  declare module.exports: $Exports<'react-bootstrap/es/HelpBlock'>;
}
declare module 'react-bootstrap/es/Image.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Image'>;
}
declare module 'react-bootstrap/es/index.js' {
  declare module.exports: $Exports<'react-bootstrap/es/index'>;
}
declare module 'react-bootstrap/es/InputGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/es/InputGroup'>;
}
declare module 'react-bootstrap/es/InputGroupAddon.js' {
  declare module.exports: $Exports<'react-bootstrap/es/InputGroupAddon'>;
}
declare module 'react-bootstrap/es/InputGroupButton.js' {
  declare module.exports: $Exports<'react-bootstrap/es/InputGroupButton'>;
}
declare module 'react-bootstrap/es/Jumbotron.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Jumbotron'>;
}
declare module 'react-bootstrap/es/Label.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Label'>;
}
declare module 'react-bootstrap/es/ListGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ListGroup'>;
}
declare module 'react-bootstrap/es/ListGroupItem.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ListGroupItem'>;
}
declare module 'react-bootstrap/es/Media.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Media'>;
}
declare module 'react-bootstrap/es/MediaBody.js' {
  declare module.exports: $Exports<'react-bootstrap/es/MediaBody'>;
}
declare module 'react-bootstrap/es/MediaHeading.js' {
  declare module.exports: $Exports<'react-bootstrap/es/MediaHeading'>;
}
declare module 'react-bootstrap/es/MediaLeft.js' {
  declare module.exports: $Exports<'react-bootstrap/es/MediaLeft'>;
}
declare module 'react-bootstrap/es/MediaList.js' {
  declare module.exports: $Exports<'react-bootstrap/es/MediaList'>;
}
declare module 'react-bootstrap/es/MediaListItem.js' {
  declare module.exports: $Exports<'react-bootstrap/es/MediaListItem'>;
}
declare module 'react-bootstrap/es/MediaRight.js' {
  declare module.exports: $Exports<'react-bootstrap/es/MediaRight'>;
}
declare module 'react-bootstrap/es/MenuItem.js' {
  declare module.exports: $Exports<'react-bootstrap/es/MenuItem'>;
}
declare module 'react-bootstrap/es/Modal.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Modal'>;
}
declare module 'react-bootstrap/es/ModalBody.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ModalBody'>;
}
declare module 'react-bootstrap/es/ModalDialog.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ModalDialog'>;
}
declare module 'react-bootstrap/es/ModalFooter.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ModalFooter'>;
}
declare module 'react-bootstrap/es/ModalHeader.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ModalHeader'>;
}
declare module 'react-bootstrap/es/ModalTitle.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ModalTitle'>;
}
declare module 'react-bootstrap/es/Nav.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Nav'>;
}
declare module 'react-bootstrap/es/Navbar.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Navbar'>;
}
declare module 'react-bootstrap/es/NavbarBrand.js' {
  declare module.exports: $Exports<'react-bootstrap/es/NavbarBrand'>;
}
declare module 'react-bootstrap/es/NavbarCollapse.js' {
  declare module.exports: $Exports<'react-bootstrap/es/NavbarCollapse'>;
}
declare module 'react-bootstrap/es/NavbarHeader.js' {
  declare module.exports: $Exports<'react-bootstrap/es/NavbarHeader'>;
}
declare module 'react-bootstrap/es/NavbarToggle.js' {
  declare module.exports: $Exports<'react-bootstrap/es/NavbarToggle'>;
}
declare module 'react-bootstrap/es/NavDropdown.js' {
  declare module.exports: $Exports<'react-bootstrap/es/NavDropdown'>;
}
declare module 'react-bootstrap/es/NavItem.js' {
  declare module.exports: $Exports<'react-bootstrap/es/NavItem'>;
}
declare module 'react-bootstrap/es/Overlay.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Overlay'>;
}
declare module 'react-bootstrap/es/OverlayTrigger.js' {
  declare module.exports: $Exports<'react-bootstrap/es/OverlayTrigger'>;
}
declare module 'react-bootstrap/es/PageHeader.js' {
  declare module.exports: $Exports<'react-bootstrap/es/PageHeader'>;
}
declare module 'react-bootstrap/es/PageItem.js' {
  declare module.exports: $Exports<'react-bootstrap/es/PageItem'>;
}
declare module 'react-bootstrap/es/Pager.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Pager'>;
}
declare module 'react-bootstrap/es/PagerItem.js' {
  declare module.exports: $Exports<'react-bootstrap/es/PagerItem'>;
}
declare module 'react-bootstrap/es/Pagination.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Pagination'>;
}
declare module 'react-bootstrap/es/PaginationButton.js' {
  declare module.exports: $Exports<'react-bootstrap/es/PaginationButton'>;
}
declare module 'react-bootstrap/es/Panel.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Panel'>;
}
declare module 'react-bootstrap/es/PanelGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/es/PanelGroup'>;
}
declare module 'react-bootstrap/es/Popover.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Popover'>;
}
declare module 'react-bootstrap/es/ProgressBar.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ProgressBar'>;
}
declare module 'react-bootstrap/es/Radio.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Radio'>;
}
declare module 'react-bootstrap/es/ResponsiveEmbed.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ResponsiveEmbed'>;
}
declare module 'react-bootstrap/es/Row.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Row'>;
}
declare module 'react-bootstrap/es/SafeAnchor.js' {
  declare module.exports: $Exports<'react-bootstrap/es/SafeAnchor'>;
}
declare module 'react-bootstrap/es/SplitButton.js' {
  declare module.exports: $Exports<'react-bootstrap/es/SplitButton'>;
}
declare module 'react-bootstrap/es/SplitToggle.js' {
  declare module.exports: $Exports<'react-bootstrap/es/SplitToggle'>;
}
declare module 'react-bootstrap/es/Tab.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Tab'>;
}
declare module 'react-bootstrap/es/TabContainer.js' {
  declare module.exports: $Exports<'react-bootstrap/es/TabContainer'>;
}
declare module 'react-bootstrap/es/TabContent.js' {
  declare module.exports: $Exports<'react-bootstrap/es/TabContent'>;
}
declare module 'react-bootstrap/es/Table.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Table'>;
}
declare module 'react-bootstrap/es/TabPane.js' {
  declare module.exports: $Exports<'react-bootstrap/es/TabPane'>;
}
declare module 'react-bootstrap/es/Tabs.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Tabs'>;
}
declare module 'react-bootstrap/es/Thumbnail.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Thumbnail'>;
}
declare module 'react-bootstrap/es/ToggleButton.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ToggleButton'>;
}
declare module 'react-bootstrap/es/ToggleButtonGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/es/ToggleButtonGroup'>;
}
declare module 'react-bootstrap/es/Tooltip.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Tooltip'>;
}
declare module 'react-bootstrap/es/utils/bootstrapUtils.js' {
  declare module.exports: $Exports<'react-bootstrap/es/utils/bootstrapUtils'>;
}
declare module 'react-bootstrap/es/utils/capitalize.js' {
  declare module.exports: $Exports<'react-bootstrap/es/utils/capitalize'>;
}
declare module 'react-bootstrap/es/utils/createChainedFunction.js' {
  declare module.exports: $Exports<'react-bootstrap/es/utils/createChainedFunction'>;
}
declare module 'react-bootstrap/es/utils/deprecationWarning.js' {
  declare module.exports: $Exports<'react-bootstrap/es/utils/deprecationWarning'>;
}
declare module 'react-bootstrap/es/utils/index.js' {
  declare module.exports: $Exports<'react-bootstrap/es/utils/index'>;
}
declare module 'react-bootstrap/es/utils/PropTypes.js' {
  declare module.exports: $Exports<'react-bootstrap/es/utils/PropTypes'>;
}
declare module 'react-bootstrap/es/utils/splitComponentProps.js' {
  declare module.exports: $Exports<'react-bootstrap/es/utils/splitComponentProps'>;
}
declare module 'react-bootstrap/es/utils/StyleConfig.js' {
  declare module.exports: $Exports<'react-bootstrap/es/utils/StyleConfig'>;
}
declare module 'react-bootstrap/es/utils/TransitionEvents.js' {
  declare module.exports: $Exports<'react-bootstrap/es/utils/TransitionEvents'>;
}
declare module 'react-bootstrap/es/utils/ValidComponentChildren.js' {
  declare module.exports: $Exports<'react-bootstrap/es/utils/ValidComponentChildren'>;
}
declare module 'react-bootstrap/es/Well.js' {
  declare module.exports: $Exports<'react-bootstrap/es/Well'>;
}
declare module 'react-bootstrap/lib/Accordion.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Accordion'>;
}
declare module 'react-bootstrap/lib/Alert.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Alert'>;
}
declare module 'react-bootstrap/lib/Badge.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Badge'>;
}
declare module 'react-bootstrap/lib/Breadcrumb.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Breadcrumb'>;
}
declare module 'react-bootstrap/lib/BreadcrumbItem.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/BreadcrumbItem'>;
}
declare module 'react-bootstrap/lib/Button.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Button'>;
}
declare module 'react-bootstrap/lib/ButtonGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ButtonGroup'>;
}
declare module 'react-bootstrap/lib/ButtonToolbar.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ButtonToolbar'>;
}
declare module 'react-bootstrap/lib/Carousel.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Carousel'>;
}
declare module 'react-bootstrap/lib/CarouselCaption.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/CarouselCaption'>;
}
declare module 'react-bootstrap/lib/CarouselItem.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/CarouselItem'>;
}
declare module 'react-bootstrap/lib/Checkbox.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Checkbox'>;
}
declare module 'react-bootstrap/lib/Clearfix.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Clearfix'>;
}
declare module 'react-bootstrap/lib/CloseButton.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/CloseButton'>;
}
declare module 'react-bootstrap/lib/Col.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Col'>;
}
declare module 'react-bootstrap/lib/Collapse.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Collapse'>;
}
declare module 'react-bootstrap/lib/ControlLabel.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ControlLabel'>;
}
declare module 'react-bootstrap/lib/Dropdown.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Dropdown'>;
}
declare module 'react-bootstrap/lib/DropdownButton.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/DropdownButton'>;
}
declare module 'react-bootstrap/lib/DropdownMenu.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/DropdownMenu'>;
}
declare module 'react-bootstrap/lib/DropdownToggle.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/DropdownToggle'>;
}
declare module 'react-bootstrap/lib/Fade.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Fade'>;
}
declare module 'react-bootstrap/lib/Form.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Form'>;
}
declare module 'react-bootstrap/lib/FormControl.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/FormControl'>;
}
declare module 'react-bootstrap/lib/FormControlFeedback.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/FormControlFeedback'>;
}
declare module 'react-bootstrap/lib/FormControlStatic.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/FormControlStatic'>;
}
declare module 'react-bootstrap/lib/FormGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/FormGroup'>;
}
declare module 'react-bootstrap/lib/Glyphicon.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Glyphicon'>;
}
declare module 'react-bootstrap/lib/Grid.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Grid'>;
}
declare module 'react-bootstrap/lib/HelpBlock.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/HelpBlock'>;
}
declare module 'react-bootstrap/lib/Image.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Image'>;
}
declare module 'react-bootstrap/lib/index.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/index'>;
}
declare module 'react-bootstrap/lib/InputGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/InputGroup'>;
}
declare module 'react-bootstrap/lib/InputGroupAddon.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/InputGroupAddon'>;
}
declare module 'react-bootstrap/lib/InputGroupButton.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/InputGroupButton'>;
}
declare module 'react-bootstrap/lib/Jumbotron.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Jumbotron'>;
}
declare module 'react-bootstrap/lib/Label.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Label'>;
}
declare module 'react-bootstrap/lib/ListGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ListGroup'>;
}
declare module 'react-bootstrap/lib/ListGroupItem.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ListGroupItem'>;
}
declare module 'react-bootstrap/lib/Media.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Media'>;
}
declare module 'react-bootstrap/lib/MediaBody.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/MediaBody'>;
}
declare module 'react-bootstrap/lib/MediaHeading.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/MediaHeading'>;
}
declare module 'react-bootstrap/lib/MediaLeft.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/MediaLeft'>;
}
declare module 'react-bootstrap/lib/MediaList.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/MediaList'>;
}
declare module 'react-bootstrap/lib/MediaListItem.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/MediaListItem'>;
}
declare module 'react-bootstrap/lib/MediaRight.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/MediaRight'>;
}
declare module 'react-bootstrap/lib/MenuItem.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/MenuItem'>;
}
declare module 'react-bootstrap/lib/Modal.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Modal'>;
}
declare module 'react-bootstrap/lib/ModalBody.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ModalBody'>;
}
declare module 'react-bootstrap/lib/ModalDialog.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ModalDialog'>;
}
declare module 'react-bootstrap/lib/ModalFooter.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ModalFooter'>;
}
declare module 'react-bootstrap/lib/ModalHeader.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ModalHeader'>;
}
declare module 'react-bootstrap/lib/ModalTitle.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ModalTitle'>;
}
declare module 'react-bootstrap/lib/Nav.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Nav'>;
}
declare module 'react-bootstrap/lib/Navbar.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Navbar'>;
}
declare module 'react-bootstrap/lib/NavbarBrand.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/NavbarBrand'>;
}
declare module 'react-bootstrap/lib/NavbarCollapse.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/NavbarCollapse'>;
}
declare module 'react-bootstrap/lib/NavbarHeader.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/NavbarHeader'>;
}
declare module 'react-bootstrap/lib/NavbarToggle.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/NavbarToggle'>;
}
declare module 'react-bootstrap/lib/NavDropdown.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/NavDropdown'>;
}
declare module 'react-bootstrap/lib/NavItem.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/NavItem'>;
}
declare module 'react-bootstrap/lib/Overlay.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Overlay'>;
}
declare module 'react-bootstrap/lib/OverlayTrigger.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/OverlayTrigger'>;
}
declare module 'react-bootstrap/lib/PageHeader.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/PageHeader'>;
}
declare module 'react-bootstrap/lib/PageItem.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/PageItem'>;
}
declare module 'react-bootstrap/lib/Pager.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Pager'>;
}
declare module 'react-bootstrap/lib/PagerItem.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/PagerItem'>;
}
declare module 'react-bootstrap/lib/Pagination.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Pagination'>;
}
declare module 'react-bootstrap/lib/PaginationButton.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/PaginationButton'>;
}
declare module 'react-bootstrap/lib/Panel.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Panel'>;
}
declare module 'react-bootstrap/lib/PanelGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/PanelGroup'>;
}
declare module 'react-bootstrap/lib/Popover.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Popover'>;
}
declare module 'react-bootstrap/lib/ProgressBar.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ProgressBar'>;
}
declare module 'react-bootstrap/lib/Radio.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Radio'>;
}
declare module 'react-bootstrap/lib/ResponsiveEmbed.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ResponsiveEmbed'>;
}
declare module 'react-bootstrap/lib/Row.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Row'>;
}
declare module 'react-bootstrap/lib/SafeAnchor.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/SafeAnchor'>;
}
declare module 'react-bootstrap/lib/SplitButton.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/SplitButton'>;
}
declare module 'react-bootstrap/lib/SplitToggle.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/SplitToggle'>;
}
declare module 'react-bootstrap/lib/Tab.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Tab'>;
}
declare module 'react-bootstrap/lib/TabContainer.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/TabContainer'>;
}
declare module 'react-bootstrap/lib/TabContent.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/TabContent'>;
}
declare module 'react-bootstrap/lib/Table.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Table'>;
}
declare module 'react-bootstrap/lib/TabPane.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/TabPane'>;
}
declare module 'react-bootstrap/lib/Tabs.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Tabs'>;
}
declare module 'react-bootstrap/lib/Thumbnail.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Thumbnail'>;
}
declare module 'react-bootstrap/lib/ToggleButton.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ToggleButton'>;
}
declare module 'react-bootstrap/lib/ToggleButtonGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/ToggleButtonGroup'>;
}
declare module 'react-bootstrap/lib/Tooltip.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Tooltip'>;
}
declare module 'react-bootstrap/lib/utils/bootstrapUtils.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/utils/bootstrapUtils'>;
}
declare module 'react-bootstrap/lib/utils/capitalize.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/utils/capitalize'>;
}
declare module 'react-bootstrap/lib/utils/createChainedFunction.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/utils/createChainedFunction'>;
}
declare module 'react-bootstrap/lib/utils/deprecationWarning.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/utils/deprecationWarning'>;
}
declare module 'react-bootstrap/lib/utils/index.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/utils/index'>;
}
declare module 'react-bootstrap/lib/utils/PropTypes.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/utils/PropTypes'>;
}
declare module 'react-bootstrap/lib/utils/splitComponentProps.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/utils/splitComponentProps'>;
}
declare module 'react-bootstrap/lib/utils/StyleConfig.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/utils/StyleConfig'>;
}
declare module 'react-bootstrap/lib/utils/TransitionEvents.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/utils/TransitionEvents'>;
}
declare module 'react-bootstrap/lib/utils/ValidComponentChildren.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/utils/ValidComponentChildren'>;
}
declare module 'react-bootstrap/lib/Well.js' {
  declare module.exports: $Exports<'react-bootstrap/lib/Well'>;
}
