// flow-typed signature: eb17d8c57d7d05c4c680c862047d5cb5
// flow-typed version: <<STUB>>/react-plotly.js_v^2.2.0/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-plotly.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-plotly.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-plotly.js/dist/create-plotly-component' {
  declare module.exports: any;
}

declare module 'react-plotly.js/dist/create-plotly-component.min' {
  declare module.exports: any;
}

declare module 'react-plotly.js/factory' {
  declare module.exports: any;
}

declare module 'react-plotly.js/react-plotly' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-plotly.js/dist/create-plotly-component.js' {
  declare module.exports: $Exports<'react-plotly.js/dist/create-plotly-component'>;
}
declare module 'react-plotly.js/dist/create-plotly-component.min.js' {
  declare module.exports: $Exports<'react-plotly.js/dist/create-plotly-component.min'>;
}
declare module 'react-plotly.js/factory.js' {
  declare module.exports: $Exports<'react-plotly.js/factory'>;
}
declare module 'react-plotly.js/react-plotly.js' {
  declare module.exports: $Exports<'react-plotly.js/react-plotly'>;
}
