/**
 * Flowtype definitions for index.ts
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.10.0
 */

declare module 'react-select-event' {
  declare module.exports: {
    select: (
      HTMLElement,
      optionOrOptions: string | RegExp | Array<string | RegExp>
    ) => Promise<void>,
    create: (
      input: HTMLElement,
      option: string,
      createOptionText: string | RegExp,
    ) => Promise<void>,
    clearFirst: (input: HTMLElement) => Promise<void>,
    clearAll: (input: HTMLElement) => Promise<void>,
    openMenu: (input: HTMLElement) => Promise<void>,
  }
}
