module.exports = [
  'jquery',
  'create-react-class',
  'deep-equal',
  'react',
  'react-dom',
  'react-addons-pure-render-mixin',
  'react-bootstrap',
  'react-router',
  'react-router-bootstrap',
  'reflux',
  'reflux-core',
  'moment',
  'moment-timezone',
];
