module.exports = [
  'jquery',
  'react',
  'react-dom',
  'react-addons-pure-render-mixin',
  'react-bootstrap',
  'react-router',
  'react-router-bootstrap',
  'react-redux',
  'redux',
  'reflux',
  'reflux-core',
  'moment',
  'moment-timezone',
];
