module.exports = [
  'chroma-js',
  'create-react-class',
  'formik',
  'jquery',
  'leaflet',
  'moment-timezone',
  'moment',
  'react-bootstrap',
  'react-dom',
  'react-router-bootstrap',
  'react-router',
  'react',
  'reflux-core',
  'reflux',
  'styled-components',
];
