/*
 * Copyright (C) 2020 Graylog, Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the Server Side Public License, version 1,
 * as published by MongoDB, Inc.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Server Side Public License for more details.
 *
 * You should have received a copy of the Server Side Public License
 * along with this program. If not, see
 * <http://www.mongodb.com/licensing/server-side-public-license>.
 */

export type SizeProp = 'xs' | 'sm' | 'lg' | 'xl' | '2x' | '3x' | '4x' | '5x'

export type IconName = 'tamper_detection_off' |
  'crisis_alert' |
  'styler' |
  'trip_origin' |
  'flashlight_on' |
  'ramp_right' |
  'indeterminate_question_box' |
  'backup' |
  'aod' |
  'bike_scooter' |
  'add_ad' |
  'mindfulness' |
  'energy_savings_leaf' |
  'car_crash' |
  'push_pin' |
  'vertical_align_center' |
  'display_settings' |
  'timelapse' |
  'decimal_decrease' |
  'local_car_wash' |
  'mixture_med' |
  'arrow_selector_tool' |
  'filter_4' |
  'bath_outdoor' |
  'motion_photos_off' |
  'network_wifi_1_bar_locked' |
  'propane_tank' |
  'abc' |
  'rv_hookup' |
  'language_french' |
  'currency_franc' |
  'chat_add_on' |
  'search' |
  'cookie_off' |
  'volume_mute' |
  'notes' |
  'sd' |
  'rheumatology' |
  'swap_vertical_circle' |
  'newsstand' |
  'cottage' |
  'google_tv_remote' |
  'task' |
  'smart_toy' |
  'highlighter_size_3' |
  'resume' |
  'find_in_page' |
  'tools_power_drill' |
  'nest_doorbell_visitor' |
  '4mp' |
  'household_supplies' |
  'circles' |
  'how_to_reg' |
  'app_shortcut' |
  'mediation' |
  'pallet' |
  'branding_watermark' |
  'do_not_disturb_off' |
  'light_mode' |
  'videocam_off' |
  'schedule_send' |
  'sports' |
  'note_add' |
  'shop_two' |
  'receipt' |
  'lightbulb_circle' |
  'production_quantity_limits' |
  'roller_shades_closed' |
  'ripples' |
  'tab_close' |
  'local_post_office' |
  'account_box' |
  'cognition' |
  'line_end_circle' |
  'genetics' |
  'subheader' |
  'humidity_mid' |
  'curtains_closed' |
  'play_circle' |
  'deployed_code_alert' |
  'no_drinks' |
  'home_max' |
  'system_update_alt' |
  'check_box_outline_blank' |
  'open_in_new_off' |
  'cloudy_snowing' |
  'water_lock' |
  'currency_yuan' |
  'fmd_bad' |
  'restart_alt' |
  'list' |
  'table_lamp' |
  'gas_meter' |
  'sound_sampler' |
  'counter_5' |
  'satellite_alt' |
  'monitor_heart' |
  'flip_to_front' |
  'power_input' |
  'prompt_suggestion' |
  'view_kanban' |
  'outlet' |
  'allergy' |
  'clock_loader_40' |
  'stream' |
  'thermometer_add' |
  'sentiment_extremely_dissatisfied' |
  'smb_share' |
  'attribution' |
  'bigtop_updates' |
  'counter_4' |
  'media_output' |
  'timer_3_select' |
  'no_accounts' |
  'mode_cool' |
  'timer_10_select' |
  'closed_caption' |
  'on_device_training' |
  '5g_mobiledata_badge' |
  'directions_alt_off' |
  'picture_as_pdf' |
  'ballot' |
  'sentiment_calm' |
  'recycling' |
  'deceased' |
  'sauna' |
  'battery_horiz_050' |
  'running_with_errors' |
  'nest_secure_alarm' |
  'unknown_2' |
  'house' |
  'search_hands_free' |
  'bed' |
  'switches' |
  'chat_apps_script' |
  'add_link' |
  'app_promo' |
  'picture_in_picture_mobile' |
  'back_to_tab' |
  'arrow_top_left' |
  'expand_circle_up' |
  'bathroom' |
  '7k_plus' |
  'swipe' |
  'brand_family' |
  'sports_golf' |
  'arrow_top_right' |
  'hourglass_top' |
  'zone_person_alert' |
  'tamper_detection_on' |
  'headphones_battery' |
  'camera_rear' |
  'onsen' |
  'oxygen_saturation' |
  'rainy_heavy' |
  'folder_managed' |
  'reset_tv' |
  'align_vertical_center' |
  'mountain_flag' |
  'keyboard_arrow_up' |
  'congenital' |
  'stadium' |
  'subscript' |
  'local_fire_department' |
  'edit_note' |
  'hdr_off_select' |
  'highlighter_size_2' |
  'sdk' |
  'earbuds_battery' |
  'qr_code_2_add' |
  'emergency_heat_2' |
  'baby_changing_station' |
  'savings' |
  'pause_circle' |
  'your_trips' |
  'local_taxi' |
  'bottom_panel_open' |
  'sentiment_sad' |
  'target' |
  'hallway' |
  'energy_program_time_used' |
  'rotate_90_degrees_cw' |
  'line_start_arrow' |
  'hearing_disabled' |
  'task_alt' |
  'wifi_tethering' |
  '2k' |
  'filter_5' |
  'airplay' |
  'support_agent' |
  'broken_image' |
  'remember_me' |
  'trending_flat' |
  'data_loss_prevention' |
  'auto_read_pause' |
  'ink_highlighter_move' |
  'markdown_paste' |
  'backlight_low' |
  'forward_5' |
  'blur_circular' |
  'screen_lock_landscape' |
  'arrow_drop_up' |
  'house_with_shield' |
  'filter_none' |
  'rice_bowl' |
  'pattern' |
  'language_international' |
  'browse_gallery' |
  'face' |
  'bookmark_manager' |
  'overview_key' |
  'repeat' |
  'new_label' |
  'thermostat_carbon' |
  'flight' |
  'playlist_add_circle' |
  'apps_outage' |
  '18_up_rating' |
  'landslide' |
  'perm_camera_mic' |
  'cloud_sync' |
  'google_home_devices' |
  'folder_limited' |
  'luggage' |
  'content_paste_go' |
  'touchpad_mouse_off' |
  'local_library' |
  'filter_7' |
  'lasso_select' |
  'swipe_left' |
  'hourglass' |
  'lyrics' |
  'arrow_drop_down_circle' |
  'microwave' |
  'atm' |
  'account_tree' |
  'straighten' |
  'public' |
  'border_clear' |
  'stay_current_landscape' |
  'watch_button_press' |
  'magnification_small' |
  'moving' |
  'video_stable' |
  'format_letter_spacing_wider' |
  'emergency' |
  'network_intelligence_history' |
  'text_select_move_forward_character' |
  'stethoscope_arrow' |
  'add_to_drive' |
  'camera_outdoor' |
  'supervised_user_circle_off' |
  'padding' |
  'south' |
  'man_4' |
  'volcano' |
  'perm_media' |
  'reply' |
  'unpublished' |
  'text_select_jump_to_beginning' |
  'sound_detection_loud_sound' |
  'signal_cellular_off' |
  'insert_text' |
  'fiber_smart_record' |
  'assignment_ind' |
  'lab_profile' |
  'doorbell_3p' |
  'line_start_arrow_notch' |
  'heat_pump_balance' |
  'numbers' |
  'directory_sync' |
  'perm_contact_calendar' |
  'mode_fan' |
  'monochrome_photos' |
  'endocrinology' |
  'distance' |
  'battery_profile' |
  'settings_heart' |
  'bottom_app_bar' |
  'arrow_outward' |
  'play_pause' |
  'monitoring' |
  'settings_slow_motion' |
  'groups_2' |
  'clock_loader_80' |
  'phone_missed' |
  'sentiment_worried' |
  'variables' |
  'dining' |
  'battery_1_bar' |
  'book_4' |
  'crop_portrait' |
  'autopause' |
  'house_siding' |
  'translate' |
  'approval' |
  'counter_6' |
  'tv_guide' |
  'assistant_device' |
  'neurology' |
  'view_comfy_alt' |
  'moved_location' |
  'javascript' |
  'play_lesson' |
  '3d_rotation' |
  'location_searching' |
  'work_update' |
  'battery_plus' |
  'code_blocks' |
  'fluid_med' |
  'bottom_sheets' |
  'grid_3x3_off' |
  'for_you' |
  'mode_comment' |
  'network_wifi' |
  'wb_auto' |
  'home_and_garden' |
  'move_group' |
  'full_stacked_bar_chart' |
  'hearing' |
  'shield_with_heart' |
  'taxi_alert' |
  'counter_7' |
  'person_search' |
  'font_download' |
  'domain_verification_off' |
  'grid_guides' |
  'event_repeat' |
  'agriculture' |
  'settings_cinematic_blur' |
  'book_5' |
  'doorbell' |
  'charging_station' |
  'umbrella' |
  'run_circle' |
  'remove_road' |
  'highlight' |
  'tire_repair' |
  'groups_3' |
  'blind' |
  'explore_off' |
  'position_top_right' |
  'battery_charging_20' |
  'fullscreen' |
  'arrow_and_edge' |
  'local_activity' |
  'sunny_snowing' |
  'arrow_circle_right' |
  'file_map' |
  'frame_source' |
  'crop_square' |
  'swap_calls' |
  'replay_30' |
  'r_mobiledata' |
  'next_plan' |
  'missing_controller' |
  'toolbar' |
  'shoppingmode' |
  'align_flex_start' |
  'assistant_direction' |
  'shield_question' |
  'timer_3_alt_1' |
  'instant_mix' |
  'all_inbox' |
  'shift' |
  'av_timer' |
  'restaurant' |
  'fireplace' |
  'directions_boat' |
  'request_page' |
  'smart_display' |
  'tab' |
  'door_sensor' |
  'new_window' |
  'mark_chat_read' |
  'commit' |
  '18mp' |
  'panorama' |
  'screenshot' |
  'highlighter_size_1' |
  'pool' |
  'width_wide' |
  'sync_lock' |
  'android' |
  'media_output_off' |
  'draw' |
  'co2' |
  'note_stack' |
  'security_key' |
  'playing_cards' |
  'water_pump' |
  'order_play' |
  'nest_cam_wired_stand' |
  'shield_person' |
  'sign_language' |
  'roofing' |
  'filter_6' |
  'view_timeline' |
  '6mp' |
  'thumb_down' |
  'circle' |
  'book_online' |
  'http' |
  'e911_emergency' |
  'laps' |
  'stroke_full' |
  'rectangle' |
  'vertical_split' |
  'outgoing_mail' |
  'key_visualizer' |
  'health_and_beauty' |
  'volume_up' |
  'person' |
  'desktop_mac' |
  'girl' |
  'airline_seat_recline_extra' |
  'home' |
  'nest_cam_stand' |
  'shop' |
  'picture_in_picture_center' |
  'inventory_2' |
  'copyright' |
  'mimo' |
  'gallery_thumbnail' |
  'nest_clock_farsight_digital' |
  'step_into' |
  'rear_camera' |
  '1k_plus' |
  'sports_volleyball' |
  'partner_exchange' |
  'video_chat' |
  'holiday_village' |
  'network_wifi_1_bar' |
  '21mp' |
  'smartphone' |
  'flight_takeoff' |
  'directions_railway' |
  'conditions' |
  'user_attributes' |
  'select_window_off' |
  'filter_2' |
  'deployed_code' |
  'dock_to_right' |
  'logo_dev' |
  'sliders' |
  'assistant_navigation' |
  'lock_open_right' |
  'top_panel_open' |
  'shutter_speed_add' |
  'grading' |
  'screen_record' |
  'clear_night' |
  'attach_email' |
  'lab_research' |
  'demography' |
  'equal' |
  'format_align_center' |
  'fastfood' |
  'touchpad_mouse' |
  'tooltip' |
  'shopping_bag' |
  'function' |
  'splitscreen_right' |
  'eject' |
  'highlighter_size_5' |
  'exposure_plus_1' |
  'flag_circle' |
  'apparel' |
  'battery_0_bar' |
  'personal_bag_question' |
  'contact_page' |
  'forward_10' |
  'festival' |
  'texture_add' |
  'backpack' |
  'potted_plant' |
  'pulmonology' |
  'comment_bank' |
  'logout' |
  'battery_charging_30' |
  'share_location' |
  'mode_fan_off' |
  'no_crash' |
  '2mp' |
  'signal_cellular_add' |
  'keyboard_double_arrow_left' |
  'format_text_overflow' |
  'hexagon' |
  'audio_file' |
  'tactic' |
  'edit_notifications' |
  'chronic' |
  'responsive_layout' |
  'connecting_airports' |
  'pest_control' |
  'turn_left' |
  'light_off' |
  'unknown_5' |
  'local_pizza' |
  'audio_description' |
  'iframe_off' |
  'tools_installation_kit' |
  'info_i' |
  'filter_b_and_w' |
  'package_2' |
  'counter_3' |
  'chat_info' |
  'text_rotation_angleup' |
  'edit_location_alt' |
  'departure_board' |
  'genres' |
  'forest' |
  'overview' |
  'model_training' |
  'ring_volume' |
  'water_ec' |
  'dock' |
  'signpost' |
  'calendar_view_day' |
  'counter_2' |
  'magnification_large' |
  'supervised_user_circle' |
  'accessible_forward' |
  'local_cafe' |
  'candle' |
  'photo_camera_back' |
  'amend' |
  'nfc' |
  'width_normal' |
  'face_retouching_off' |
  'nest_wifi_point' |
  'cancel' |
  'clock_loader_90' |
  'usb' |
  'filter_drama' |
  'language_japanese_kana' |
  'service_toolbox' |
  'tapas' |
  'battery_full_alt' |
  'mood' |
  'ar_stickers' |
  'frame_reload' |
  'phone_in_talk' |
  'accessibility_new' |
  'nightlight' |
  'fast_rewind' |
  'art_track' |
  'ad_units' |
  'mode_heat' |
  'youtube_activity' |
  'blur_off' |
  'cooking' |
  'outdoor_grill' |
  'bedtime' |
  'brightness_medium' |
  'no_encryption' |
  'contact_emergency' |
  'roller_skating' |
  'ent' |
  'calendar_add_on' |
  'cool_to_dry' |
  'camping' |
  'auto_stories' |
  'table_rows_narrow' |
  'home_work' |
  'h_plus_mobiledata_badge' |
  'print_disabled' |
  'format_image_left' |
  'blur_medium' |
  'border_left' |
  'bia' |
  'alarm_on' |
  'church' |
  'emoji_objects' |
  'crop' |
  'highlighter_size_4' |
  'swap_driving_apps_wheel' |
  'airline_seat_individual_suite' |
  'cookie' |
  'bar_chart_4_bars' |
  'cast_for_education' |
  'adf_scanner' |
  'tag' |
  'storefront' |
  'decimal_increase' |
  'frame_person_off' |
  'audio_video_receiver' |
  'animation' |
  'keyboard_alt' |
  'partly_cloudy_night' |
  'toggle_off' |
  'hot_tub' |
  'format_letter_spacing_wide' |
  'text_rotate_vertical' |
  'hdr_plus' |
  'pace' |
  'step' |
  'upload_2' |
  'airplane_ticket' |
  'check_in_out' |
  'self_improvement' |
  'hdr_auto' |
  'safety_check' |
  'settings_phone' |
  'folder_delete' |
  'nest_cam_floodlight' |
  'liquor' |
  'unfold_more_double' |
  'filter_3' |
  'credit_card' |
  'heap_snapshot_large' |
  'arrow_downward' |
  'monetization_on' |
  'pending_actions' |
  'arrow_back' |
  'reopen_window' |
  'quick_reference_all' |
  'visibility' |
  'saved_search' |
  'youtube_searched_for' |
  'border_outer' |
  'send_and_archive' |
  'breakfast_dining' |
  'cloud_download' |
  'unfold_less_double' |
  'upcoming' |
  'shower' |
  'call_made' |
  'hvac' |
  'gpp_maybe' |
  'alternate_email' |
  'brightness_low' |
  'speed_2x' |
  'downloading' |
  'menstrual_health' |
  'strikethrough_s' |
  'select_to_speak' |
  'filter_alt_off' |
  'motion_sensor_urgent' |
  'settings_night_sight' |
  'reset_image' |
  'currency_pound' |
  'filter_1' |
  '3k' |
  'volume_down_alt' |
  'east' |
  'label' |
  'folder_special' |
  'filter_tilt_shift' |
  'change_history' |
  'language_us_dvorak' |
  'more_down' |
  'map' |
  'horizontal_rule' |
  'inbox' |
  'sim_card' |
  'domino_mask' |
  '60fps' |
  'short_stay' |
  'soup_kitchen' |
  'network_manage' |
  'military_tech' |
  'loupe' |
  'power' |
  'trolley' |
  'verified' |
  'database' |
  'chat_bubble' |
  'help_center' |
  'mms' |
  'turn_sharp_right' |
  'femur_alt' |
  'wifi_find' |
  'captive_portal' |
  'bakery_dining' |
  'rss_feed' |
  'screen_search_desktop' |
  'multicooker' |
  'slide_library' |
  'person_cancel' |
  'north_east' |
  'exposure_plus_2' |
  'side_navigation' |
  'border_all' |
  'card_travel' |
  'transform' |
  'manage_search' |
  'chips' |
  'outbox_alt' |
  'sports_cricket' |
  'nest_thermostat_gen_3' |
  'man_2' |
  'mystery' |
  'swords' |
  'phone_enabled' |
  'sentiment_satisfied' |
  'earbuds' |
  'do_not_disturb_on' |
  'self_care' |
  'language_chinese_array' |
  'keyboard_option_key' |
  'glass_cup' |
  'downhill_skiing' |
  'speed' |
  'wall_art' |
  'nest_wake_on_approach' |
  'tornado' |
  'travel_explore' |
  'center_focus_strong' |
  'link_off' |
  '1x_mobiledata_badge' |
  'sprinkler' |
  'wb_iridescent' |
  'book_2' |
  'stylus_laser_pointer' |
  'auto_awesome_motion' |
  'collections_bookmark' |
  'scatter_plot' |
  'monitor_weight' |
  'hevc' |
  'zoom_in' |
  'person_add_disabled' |
  'sentiment_very_dissatisfied' |
  'kitesurfing' |
  'humerus_alt' |
  'spatial_tracking' |
  'dynamic_form' |
  'folder_supervised' |
  'male' |
  'two_pager' |
  'mic_double' |
  'counter_0' |
  'helicopter' |
  'ev_charger' |
  'counter_1' |
  'subtitles' |
  'shield_moon' |
  'format_align_left' |
  'chess' |
  'rebase' |
  'error_med' |
  'align_justify_flex_start' |
  'library_add_check' |
  'home_max_dots' |
  'desktop_access_disabled' |
  'person_apron' |
  'devices' |
  'rtt' |
  'voicemail' |
  'cinematic_blur' |
  'nest_cam_wall_mount' |
  'call_missed_outgoing' |
  'data_usage' |
  'go_to_line' |
  'center_focus_weak' |
  'nest_thermostat_zirconium_eu' |
  'book_3' |
  'contrast' |
  'trail_length_short' |
  'forward_circle' |
  'interactive_space' |
  'variable_remove' |
  'signal_wifi_off' |
  'local_dining' |
  'ecg' |
  'event_busy' |
  'dock_to_left' |
  'custom_typography' |
  'right_panel_close' |
  'devices_fold' |
  'terminal' |
  'masked_transitions' |
  'man_3' |
  'table_chart_view' |
  'strategy' |
  'emergency_recording' |
  'add_card' |
  'perm_scan_wifi' |
  'move' |
  'remove_moderator' |
  'inbox_customize' |
  'nest_protect' |
  'maximize' |
  'match_case' |
  'list_alt_add' |
  'tab_move' |
  'radar' |
  'splitscreen_top' |
  'format_quote' |
  'humidity_low' |
  'language_us' |
  '23mp' |
  'signal_wifi_0_bar' |
  'ad_off' |
  'live_help' |
  'language_us_colemak' |
  'network_locked' |
  'align_space_between' |
  'home_repair_service' |
  'disabled_by_default' |
  'mark_as_unread' |
  'install_mobile' |
  'energy' |
  'prayer_times' |
  'sprint' |
  'photo_album' |
  'video_camera_back' |
  'safety_divider' |
  'add_moderator' |
  'spoke' |
  'notifications_off' |
  'directions_bus' |
  'backlight_high_off' |
  'zoom_out_map' |
  'cloud_done' |
  'signal_cellular_nodata' |
  'stroller' |
  'medical_services' |
  'dataset_linked' |
  'ecg_heart' |
  'grade' |
  'bubble' |
  'dry' |
  'camera_roll' |
  'wrap_text' |
  'videogame_asset_off' |
  'outbound' |
  'brightness_empty' |
  'fit_screen' |
  'history_off' |
  'pulse_alert' |
  'more_time' |
  'build' |
  'personal_bag_off' |
  'post' |
  'whatshot' |
  'enterprise' |
  'top_panel_close' |
  'keyboard' |
  'stat_3' |
  'coffee_maker' |
  'tv_options_input_settings' |
  'format_strikethrough' |
  'apartment' |
  'edit_calendar' |
  'macro_auto' |
  'emergency_home' |
  'joystick' |
  'yard' |
  'voice_chat' |
  'swap_driving_apps' |
  'battery_2_bar' |
  'bedroom_child' |
  'add_task' |
  'sensor_window' |
  'fort' |
  'border_horizontal' |
  'sensors_krx' |
  'ulna_radius_alt' |
  'chromecast_2' |
  'vpn_key_alert' |
  'ulna_radius' |
  'nest_display' |
  'chip_extraction' |
  'car_rental' |
  'mode_dual' |
  'heap_snapshot_multiple' |
  'air_purifier' |
  'brightness_high' |
  'line_end_arrow' |
  'line_axis' |
  'breaking_news' |
  'wounds_injuries' |
  'surgical' |
  'lock' |
  'toys' |
  'fiber_dvr' |
  'familiar_face_and_zone' |
  'battery_very_low' |
  'sentiment_dissatisfied' |
  'nest_thermostat_e_eu' |
  'align_self_stretch' |
  'dataset' |
  'vertical_distribute' |
  'data_thresholding' |
  'backup_table' |
  'view_comfy' |
  'network_wifi_3_bar' |
  'call_log' |
  'developer_mode' |
  'subtitles_off' |
  'full_hd' |
  'phonelink_off' |
  'progress_activity' |
  'spatial_audio_off' |
  'woman_2' |
  'bookmark_added' |
  'headset_mic' |
  'rewarded_ads' |
  'text_decrease' |
  'nat' |
  'relax' |
  'water_orp' |
  'stop_circle' |
  'ramp_left' |
  'roundabout_right' |
  'cell_tower' |
  'night_sight_auto' |
  'done_outline' |
  'spo2' |
  'background_grid_small' |
  'north' |
  'directions_alt' |
  'gate' |
  '7mp' |
  'view_headline' |
  'inventory' |
  'settings_voice' |
  'energy_program_saving' |
  'key_off' |
  'developer_board' |
  'ink_pen' |
  'low_density' |
  'family_history' |
  'language_pinyin' |
  'playlist_remove' |
  'cameraswitch' |
  'diagnosis' |
  'aod_watch' |
  'type_specimen' |
  'crowdsource' |
  'comments_disabled' |
  'person_edit' |
  'sports_mma' |
  'package' |
  'water_loss' |
  'flutter' |
  'arrow_left' |
  'voting_chip' |
  'villa' |
  'devices_wearables' |
  'outpatient_med' |
  'move_up' |
  'euro' |
  'plagiarism' |
  '19mp' |
  'link' |
  'line_weight' |
  'countertops' |
  'pinch_zoom_in' |
  'buttons_alt' |
  'nest_cam_indoor' |
  'front_loader' |
  'dehaze' |
  'key' |
  'flightsmode' |
  'water_bottle_large' |
  'raw_off' |
  'settings_motion_mode' |
  'system_update' |
  'wifi_password' |
  'trending_up' |
  'crib' |
  'cloud_upload' |
  'google_wifi' |
  'settings_remote' |
  'comic_bubble' |
  'video_search' |
  'crop_free' |
  'ventilator' |
  'battery_share' |
  'label_off' |
  'network_wifi_2_bar_locked' |
  'table_rows' |
  'surround_sound' |
  'deskphone' |
  'contact_phone' |
  'dew_point' |
  'repeat_one' |
  'bathtub' |
  'nest_cam_magnet_mount' |
  'grid_on' |
  '24mp' |
  'motion_photos_on' |
  'notification_important' |
  'landscape' |
  'policy' |
  'playlist_play' |
  'text_rotation_angledown' |
  'rule' |
  '6k_plus' |
  'add_location_alt' |
  'store' |
  'file_download_done' |
  'healing' |
  'warning_off' |
  'stat_2' |
  'group_add' |
  'podcasts' |
  'brush' |
  'library_books' |
  'water_damage' |
  'tenancy' |
  '8k' |
  'view_cozy' |
  'dock_to_bottom' |
  'language_chinese_wubi' |
  'order_approve' |
  'barcode_scanner' |
  'oncology' |
  'density_large' |
  'unlicense' |
  'colorize' |
  'important_devices' |
  'cell_merge' |
  'wallpaper' |
  'markunread_mailbox' |
  'ambulance' |
  'garden_cart' |
  'wind_power' |
  'currency_ruble' |
  'badge_critical_battery' |
  'park' |
  'disabled_visible' |
  'supervisor_account' |
  'rib_cage' |
  'move_selection_down' |
  'stat_0' |
  'smoke_free' |
  'linear_scale' |
  'background_dot_small' |
  'diversity_4' |
  'wine_bar' |
  'transition_chop' |
  'dns' |
  'sports_esports' |
  'picture_in_picture' |
  'format_textdirection_r_to_l' |
  'minimize' |
  'where_to_vote' |
  'snowshoeing' |
  'photo_frame' |
  'phone_android' |
  'group' |
  'restore_from_trash' |
  'activity_zone' |
  'settings' |
  'switch_access_2' |
  'fiber_manual_record' |
  'arrows_more_up' |
  'stadia_controller' |
  'dictionary' |
  'phonelink_ring_off' |
  'barefoot' |
  'sports_football' |
  'last_page' |
  'hr_resting' |
  'close_fullscreen' |
  'question_exchange' |
  'travel' |
  'reminder' |
  'account_balance' |
  'tv_with_assistant' |
  'text_select_jump_to_end' |
  'compress' |
  'heart_check' |
  'arrow_range' |
  'remote_gen' |
  'double_arrow' |
  'steps' |
  'bottom_drawer' |
  'text_ad' |
  'directions_car' |
  'hard_drive' |
  'menu_book' |
  'stylus_note' |
  'file_upload_off' |
  'remove_from_queue' |
  'build_circle' |
  'swap_horiz' |
  '5mp' |
  'token' |
  'flights_and_hotels' |
  'collapse_content' |
  'credit_score' |
  'format_italic' |
  'join_right' |
  'movie' |
  'elevation' |
  'archive' |
  'format_color_reset' |
  'beenhere' |
  'dialer_sip' |
  'skillet' |
  'bath_private' |
  'pie_chart' |
  'question_mark' |
  'glucose' |
  'escalator_warning' |
  'polymer' |
  'screen_rotation' |
  'transition_fade' |
  'vertical_shades' |
  'turn_sharp_left' |
  'lens' |
  'collapse_all' |
  'nights_stay' |
  'clock_loader_20' |
  'outbox' |
  'transcribe' |
  'mail' |
  'school' |
  'air_freshener' |
  'nest_farsight_weather' |
  'send_money' |
  'north_west' |
  'title' |
  'sports_baseball' |
  'settings_accessibility' |
  'partly_cloudy_day' |
  'vital_signs' |
  'panorama_vertical' |
  'format_underlined' |
  'shield' |
  'download' |
  'comedy_mask' |
  'draw_abstract' |
  'currency_lira' |
  'view_stream' |
  'expand' |
  'bring_your_own_ip' |
  'donut_small' |
  'track_changes' |
  'picture_in_picture_large' |
  'memory_alt' |
  'note' |
  'pin' |
  'table_view' |
  'broadcast_on_personal' |
  'language_gb_english' |
  'west' |
  'page_info' |
  'format_paragraph' |
  'oil_barrel' |
  'weather_mix' |
  'apps' |
  'no_photography' |
  'drive_file_move' |
  'desktop_windows' |
  'missed_video_call' |
  'battery_charging_80' |
  'newsmode' |
  'video_camera_front' |
  'text_select_move_up' |
  'autofps_select' |
  'filter_center_focus' |
  'nest_heat_link_gen_3' |
  'extension_off' |
  'currency_exchange' |
  'chat_paste_go' |
  'smart_outlet' |
  'linked_services' |
  'campaign' |
  'directions_bike' |
  'laptop_chromebook' |
  'assignment_turned_in' |
  'forklift' |
  'keyboard_arrow_down' |
  'footprint' |
  'edit_location' |
  'details' |
  'hub' |
  'castle' |
  'money_off' |
  'pill_off' |
  'library_music' |
  'deblur' |
  'component_exchange' |
  'quickreply' |
  'leaderboard' |
  'tour' |
  'ink_highlighter' |
  'phonelink_lock' |
  'brightness_alert' |
  'free_cancellation' |
  'width' |
  'bolt' |
  'tv' |
  'sms' |
  'transportation' |
  'photo_camera_front' |
  '4k' |
  'swap_horizontal_circle' |
  'playlist_add' |
  'adb' |
  'desk' |
  'align_justify_space_around' |
  'align_justify_stretch' |
  'add_home' |
  'stat_1' |
  'electric_rickshaw' |
  'detector_status' |
  'location_off' |
  'air' |
  'electric_car' |
  'account_child_invert' |
  'right_panel_open' |
  'duo' |
  'photo_size_select_large' |
  'videocam' |
  'shapes' |
  'hls_off' |
  'mosque' |
  'satellite' |
  'nightlife' |
  'align_end' |
  'bar_chart' |
  'motion_photos_auto' |
  'mode_heat_cool' |
  'mp' |
  'diversity_1' |
  'directions_run' |
  'indeterminate_check_box' |
  '5k' |
  'hls' |
  'layers_clear' |
  'fire_truck' |
  'flex_direction' |
  'thunderstorm' |
  'ad' |
  'offline_share' |
  'signal_cellular_4_bar' |
  'left_panel_open' |
  'volume_off' |
  'layers' |
  'network_wifi_locked' |
  'device_reset' |
  'photo_auto_merge' |
  'battery_error' |
  'login' |
  'mode_heat_off' |
  'radio' |
  'send_to_mobile' |
  'tools_level' |
  'ink_eraser_off' |
  'local_laundry_service' |
  'cast_pause' |
  'add_location' |
  'mark_email_unread' |
  'settings_input_antenna' |
  'online_prediction' |
  'book' |
  'speaker_phone' |
  'fiber_pin' |
  'hide_source' |
  'fit_page' |
  'view_quilt' |
  'screenshot_keyboard' |
  'paid' |
  'add_shopping_cart' |
  'hotel' |
  'expand_circle_right' |
  'change_circle' |
  'picture_in_picture_small' |
  'settings_input_hdmi' |
  'donut_large' |
  'spatial_audio' |
  'priority' |
  'battery_charging_90' |
  'price_change' |
  'sensors' |
  'queue_music' |
  'skull' |
  'view_carousel' |
  'social_leaderboard' |
  'train' |
  'flaky' |
  'photo_size_select_small' |
  'pan_tool_alt' |
  'local_florist' |
  'sentiment_very_satisfied' |
  'wallet' |
  'battery_change' |
  'action_key' |
  'thermometer_gain' |
  'hand_bones' |
  'casino' |
  'calculate' |
  'close_small' |
  'health_and_safety' |
  'qr_code_2' |
  'switch_camera' |
  'phone_forwarded' |
  'colors' |
  'swipe_up_alt' |
  'movie_edit' |
  'docs_apps_script' |
  'language_spanish' |
  'coffee' |
  'bloodtype' |
  'highlight_text_cursor' |
  'dashboard' |
  'calendar_month' |
  'chevron_right' |
  'tap_and_play' |
  'place_item' |
  'code' |
  'speaker_notes_off' |
  'format_list_bulleted_add' |
  'cake' |
  'deployed_code_account' |
  'mode_night' |
  'panorama_wide_angle' |
  'enterprise_off' |
  'signal_cellular_connected_no_internet_0_bar' |
  'h_mobiledata_badge' |
  'troubleshoot' |
  'carry_on_bag_checked' |
  'history_toggle_off' |
  'severe_cold' |
  'exposure_zero' |
  'snowing_heavy' |
  'detector_co' |
  'rounded_corner' |
  'recommend' |
  'stacked_line_chart' |
  'join' |
  'format_image_right' |
  'difference' |
  'wifi_notification' |
  'gif' |
  'thermometer' |
  'admin_panel_settings' |
  'cast' |
  'move_selection_right' |
  'history_edu' |
  'flag' |
  'quick_reorder' |
  'fire_hydrant' |
  'shape_line' |
  'near_me' |
  'background_dot_large' |
  'list_alt' |
  'vape_free' |
  'wb_twilight' |
  '22mp' |
  'chevron_left' |
  'update' |
  'redeem' |
  'text_increase' |
  'preview' |
  'stacks' |
  'bungalow' |
  'mark_chat_unread' |
  'usb_off' |
  'line_style' |
  'quiet_time' |
  'event_available' |
  'ink_eraser' |
  'release_alert' |
  'digital_wellbeing' |
  'fluid_balance' |
  'circles_ext' |
  'dark_mode' |
  'turn_right' |
  'blinds' |
  'wb_sunny' |
  'doorbell_chime' |
  'emoji_events' |
  'person_play' |
  'stop' |
  'concierge' |
  'flight_land' |
  'science' |
  'bid_landscape' |
  'inpatient' |
  'newspaper' |
  'rainy_light' |
  'line_curve' |
  'export_notes' |
  'event' |
  'home_app_logo' |
  'settings_ethernet' |
  'person_raised_hand' |
  'sailing' |
  'view_compact_alt' |
  'bomb' |
  'segment' |
  'markdown' |
  'remove_shopping_cart' |
  'piano' |
  'data_table' |
  'perm_device_information' |
  'motion_photos_paused' |
  'tibia' |
  'panorama_fish_eye' |
  'forum' |
  'lock_reset' |
  'high_density' |
  'account_circle' |
  'recent_patient' |
  'do_not_step' |
  'planner_review' |
  'line_start_circle' |
  'humerus' |
  'tsv' |
  'tab_duplicate' |
  'location_disabled' |
  'arrow_right' |
  'aq_indoor' |
  'watch_screentime' |
  'support' |
  'edit_road' |
  'moving_ministry' |
  'shopping_cart_off' |
  '9k' |
  'skip_next' |
  'raw_on' |
  'app_badging' |
  'balcony' |
  'widgets' |
  'trending_down' |
  'tabs' |
  'step_over' |
  'sports_and_outdoors' |
  'work' |
  'shelves' |
  'view_compact' |
  'recent_actors' |
  'picture_in_picture_alt' |
  'bus_alert' |
  'nest_thermostat_sensor' |
  'disc_full' |
  'contract_delete' |
  'rotate_90_degrees_ccw' |
  'drag_pan' |
  'circle_notifications' |
  'wysiwyg' |
  'line_start' |
  'query_stats' |
  'passkey' |
  'fax' |
  'diversity_2' |
  'nest_cam_outdoor' |
  'medical_mask' |
  'arrow_circle_left' |
  'keyboard_hide' |
  'crop_landscape' |
  'ward' |
  'crop_16_9' |
  'factory' |
  'event_upcoming' |
  'sports_rugby' |
  'tv_gen' |
  'currency_rupee' |
  'move_to_inbox' |
  'medical_information' |
  'notifications_active' |
  '3mp' |
  'stream_apps' |
  'tab_unselected' |
  'battery_3_bar' |
  'device_thermostat' |
  'fence' |
  '3g_mobiledata_badge' |
  'workspaces' |
  'category' |
  'live_tv' |
  'trophy' |
  'screenshot_frame' |
  'handyman' |
  'reduce_capacity' |
  'keyboard_onscreen' |
  'acute' |
  'subscriptions' |
  'compost' |
  'local_pharmacy' |
  'feed' |
  'turn_slight_right' |
  'panorama_horizontal' |
  'display_external_input' |
  'border_inner' |
  'receipt_long' |
  'label_important' |
  'check' |
  'format_text_wrap' |
  'table_chart' |
  'aspect_ratio' |
  'looks_two' |
  'screenshot_region' |
  'family_star' |
  'eda' |
  'text_rotation_down' |
  'battery_charging_50' |
  'g_mobiledata_badge' |
  'density_small' |
  'warning' |
  'forms_add_on' |
  'wifi_calling' |
  'integration_instructions' |
  'notifications_paused' |
  'gradient' |
  'account_balance_wallet' |
  'apk_install' |
  'network_wifi_3_bar_locked' |
  '20mp' |
  'low_priority' |
  'business_center' |
  'family_restroom' |
  'format_align_right' |
  'domain_add' |
  'bluetooth' |
  'tv_signin' |
  'touch_app' |
  'network_wifi_2_bar' |
  'skip_previous' |
  'video_settings' |
  'install_desktop' |
  'near_me_disabled' |
  'foot_bones' |
  'call_received' |
  'headphones' |
  'highlight_keyboard_focus' |
  'space_bar' |
  'folded_hands' |
  'playlist_add_check' |
  'cancel_schedule_send' |
  'arrow_split' |
  'garage_door' |
  'party_mode' |
  'functions' |
  'privacy_tip' |
  'approval_delegation' |
  'hdr_enhanced_select' |
  'offline_bolt' |
  'upload_file' |
  'airwave' |
  'planner_banner_ad_pt' |
  'line_end_diamond' |
  'conveyor_belt' |
  'nest_gale_wifi' |
  'sensor_occupied' |
  'move_selection_up' |
  'door_sliding' |
  'temp_preferences_eco' |
  'lte_plus_mobiledata_badge' |
  'assistant_on_hub' |
  'ice_skating' |
  'priority_high' |
  'ev_station' |
  'fast_forward' |
  'calendar_today' |
  'bubble_chart' |
  'lock_open' |
  'nest_found_savings' |
  'nest_mini' |
  'wifi' |
  'altitude' |
  'macro_off' |
  'timer_off' |
  'carry_on_bag_question' |
  'import_contacts' |
  'drafts' |
  'watch' |
  'tab_recent' |
  'process_chart' |
  'keyboard_external_input' |
  'rainy_snow' |
  'other_admission' |
  'scale' |
  'add_business' |
  'add_road' |
  'pest_control_rodent' |
  'agender' |
  'nest_sunblock' |
  'play_shapes' |
  'arrow_left_alt' |
  'position_bottom_right' |
  'news' |
  'autostop' |
  'globe_uk' |
  'thermometer_loss' |
  'create_new_folder' |
  'move_item' |
  'info' |
  'format_list_numbered_rtl' |
  'keyboard_full' |
  'letter_switch' |
  'compare_arrows' |
  'stethoscope_check' |
  'drag_indicator' |
  '360' |
  'labs' |
  'sticky_note' |
  'domain' |
  'detection_and_zone' |
  'enable' |
  'carry_on_bag' |
  'cell_wifi' |
  'polyline' |
  'destruction' |
  'expand_all' |
  'hangout_video' |
  'railway_alert' |
  'shopping_cart' |
  'today' |
  'local_atm' |
  'select_all' |
  'area_chart' |
  'invert_colors' |
  'alarm_smart_wake' |
  'robot_2' |
  'palette' |
  'replay' |
  'calendar_view_month' |
  'aq' |
  'cruelty_free' |
  'find_replace' |
  'text_format' |
  'add' |
  'check_indeterminate_small' |
  'diversity_3' |
  'present_to_all' |
  'playlist_add_check_circle' |
  'hangout_video_off' |
  'directions' |
  'dvr' |
  'sports_hockey' |
  'pediatrics' |
  'car_tag' |
  'video_call' |
  'preliminary' |
  'stress_management' |
  'arrow_upward' |
  'keyboard_previous_language' |
  'group_off' |
  'signal_wifi_statusbar_not_connected' |
  'first_page' |
  'data_check' |
  'repeat_on' |
  'home_speaker' |
  'local_gas_station' |
  'sheets_rtl' |
  'close' |
  'show_chart' |
  'orders' |
  'page_control' |
  'more_horiz' |
  'toll' |
  'dialpad' |
  'time_auto' |
  'finance' |
  'format_letter_spacing_2' |
  'storm' |
  'curtains' |
  'architecture' |
  'visibility_lock' |
  'more_up' |
  'battery_saver' |
  'airplanemode_active' |
  'how_to_vote' |
  'call_missed' |
  'align_justify_flex_end' |
  'menu_open' |
  'keyboard_arrow_left' |
  'nest_thermostat' |
  'screen_lock_rotation' |
  'crop_7_5' |
  'battery_status_good' |
  'looks_3' |
  'punch_clock' |
  'view_day' |
  'mode_off_on' |
  'night_sight_auto_off' |
  'pages' |
  'shield_lock' |
  'door_front' |
  'all_inclusive' |
  'mic' |
  'kebab_dining' |
  'exposure_neg_2' |
  'help_clinic' |
  'invert_colors_off' |
  'window_open' |
  'docs_add_on' |
  'bookmark_add' |
  'splitscreen_vertical_add' |
  'night_sight_max' |
  '5k_plus' |
  'check_circle' |
  'signal_cellular_alt' |
  'tram' |
  'pending' |
  'grid_4x4' |
  'snooze' |
  'join_inner' |
  'keyboard_backspace' |
  'markdown_copy' |
  'subject' |
  'language_chinese_cangjie' |
  'pen_size_4' |
  'horizontal_distribute' |
  'share_off' |
  'sports_tennis' |
  'signature' |
  'cabin' |
  'battery_charging_60' |
  'face_3' |
  'location_city' |
  'nest_tag' |
  'deployed_code_history' |
  'event_list' |
  'add_call' |
  'app_registration' |
  'laptop_mac' |
  'hematology' |
  'folder_off' |
  'wifi_lock' |
  'shopping_cart_checkout' |
  'filter_retrolux' |
  'bluetooth_disabled' |
  'format_h4' |
  'draft' |
  'edit_off' |
  'domain_verification' |
  'autoplay' |
  'garage' |
  'readiness_score' |
  'stockpot' |
  'hand_gesture' |
  'volume_down' |
  'refresh' |
  'metabolism' |
  'opacity' |
  'format_h5' |
  'hide' |
  'monitor_weight_gain' |
  'nest_cam_iq' |
  'text_snippet' |
  'local_shipping' |
  'zone_person_urgent' |
  'search_off' |
  'stock_media' |
  'vrpano' |
  'vaping_rooms' |
  'heart_plus' |
  'amp_stories' |
  'credit_card_heart' |
  'design_services' |
  'mark_unread_chat_alt' |
  'sports_handball' |
  'person_pin_circle' |
  'tools_phillips' |
  'headset_off' |
  'exit_to_app' |
  'taunt' |
  'open_in_full' |
  'face_2' |
  'compare' |
  'no_flash' |
  'battery_6_bar' |
  'tv_off' |
  'image' |
  'expand_content' |
  'sensors_off' |
  'folder_zip' |
  'controller_gen' |
  'pen_size_5' |
  'euro_symbol' |
  'co_present' |
  'pregnancy' |
  'directions_walk' |
  'content_cut' |
  'measuring_tape' |
  'microbiology' |
  'lightbulb' |
  'arrows_more_down' |
  'attach_money' |
  'text_select_end' |
  'line_end_square' |
  'empty_dashboard' |
  'wifi_proxy' |
  'food_bank' |
  'cast_warning' |
  'zoom_in_map' |
  'view_list' |
  'view_array' |
  'save' |
  'quiz' |
  'toast' |
  'move_selection_left' |
  'award_star' |
  'ev_shadow_add' |
  'sentiment_stressed' |
  'switch_access' |
  'scan' |
  'checkroom' |
  '11mp' |
  'navigation' |
  '4g_plus_mobiledata' |
  'nest_detect' |
  'bookmarks' |
  'calendar_apps_script' |
  'favorite' |
  'signal_cellular_alt_2_bar' |
  'tab_close_right' |
  'emergency_share_off' |
  'sports_soccer' |
  'humidity_high' |
  'keyboard_return' |
  'sync_saved_locally' |
  'filter_hdr' |
  'bluetooth_drive' |
  'bedroom_baby' |
  'tv_options_edit_channels' |
  'video_file' |
  'quick_phrases' |
  'emoji_food_beverage' |
  'swap_vert' |
  'arrow_drop_down' |
  'thermometer_minus' |
  'other_houses' |
  'settings_video_camera' |
  'start' |
  'replay_5' |
  'person_check' |
  'frame_inspect' |
  'phone_iphone' |
  'scene' |
  'gite' |
  'bottom_panel_close' |
  'shuffle_on' |
  'mobile_screen_share' |
  'csv' |
  'crop_5_4' |
  'emoji_flags' |
  'expand_circle_down' |
  'vacuum' |
  'oven' |
  '13mp' |
  'navigate_before' |
  'format_indent_increase' |
  'print_lock' |
  'badge' |
  'grid_view' |
  'ev_shadow' |
  'folder_shared' |
  'location_chip' |
  'copy_all' |
  'noise_control_off' |
  'sports_kabaddi' |
  'leak_remove' |
  'point_scan' |
  '5g' |
  'move_down' |
  'medication_liquid' |
  'iframe' |
  'browse' |
  '6k' |
  'personal_places' |
  '8k_plus' |
  'sos' |
  'flash_on' |
  'file_open' |
  'assignment_add' |
  'family_link' |
  'variable_insert' |
  'manage_history' |
  'content_copy' |
  'monitor_weight_loss' |
  'device_hub' |
  'on_hub_device' |
  'airplanemode_inactive' |
  'splitscreen' |
  'exposure_neg_1' |
  'lunch_dining' |
  'gesture' |
  'wifi_2_bar' |
  'syringe' |
  'pedal_bike' |
  'surfing' |
  'pan_tool' |
  'open_in_browser' |
  'vpn_key_off' |
  'unknown_document' |
  'library_add' |
  'shift_lock' |
  'carry_on_bag_inactive' |
  'home_mini' |
  'box' |
  'earthquake' |
  'featured_seasonal_and_gifts' |
  'nearby' |
  'superscript' |
  'subdirectory_arrow_left' |
  'forward_to_inbox' |
  'density_medium' |
  'call_to_action' |
  'commute' |
  'hdr_on' |
  'alarm_add' |
  'restore_page' |
  'leak_add' |
  'hiking' |
  'style' |
  'emoticon' |
  'contract' |
  'crop_3_2' |
  'symptoms' |
  'wb_incandescent' |
  'percent' |
  'keyboard_command_key' |
  'kid_star' |
  'science_off' |
  'nest_hello_doorbell' |
  'phone_locked' |
  'square' |
  'local_drink' |
  'workspace_premium' |
  'report' |
  'format_color_text' |
  'stethoscope' |
  'step_out' |
  'drive_folder_upload' |
  'sports_martial_arts' |
  'nest_display_max' |
  'piano_off' |
  'perm_data_setting' |
  'network_node' |
  'arrow_right_alt' |
  'heap_snapshot_thumbnail' |
  'chat' |
  'phonelink_erase' |
  'barcode_reader' |
  'p2p' |
  'format_h6' |
  'signal_cellular_1_bar' |
  'early_on' |
  'local_mall' |
  'dirty_lens' |
  'child_friendly' |
  'filter_frames' |
  'person_book' |
  'screen_rotation_alt' |
  'explosion' |
  'pip' |
  'splitscreen_left' |
  'ads_click' |
  'sell' |
  'nest_connect' |
  'article' |
  'table' |
  'send' |
  'barcode' |
  'rsvp' |
  'wrong_location' |
  'boy' |
  'blur_linear' |
  'record_voice_over' |
  'hdr_plus_off' |
  'speed_0_5' |
  'keyboard_control_key' |
  'keyboard_capslock_badge' |
  'save_as' |
  'sensors_krx_off' |
  'expand_more' |
  'speaker' |
  'cardiology' |
  'explore' |
  'cases' |
  '4g_mobiledata_badge' |
  'mist' |
  'sports_basketball' |
  'publish' |
  'ophthalmology' |
  'bug_report' |
  'falling' |
  'network_cell' |
  'detector_battery' |
  'contacts_product' |
  'switch_left' |
  'feedback' |
  'auto_awesome_mosaic' |
  'shelf_auto_hide' |
  'screen_lock_portrait' |
  'card_membership' |
  'media_link' |
  'camera' |
  'detector' |
  'rotate_left' |
  'confirmation_number' |
  'source_environment' |
  'ods' |
  'assignment_return' |
  'redo' |
  'high_res' |
  'device_unknown' |
  'nephrology' |
  'format_text_clip' |
  'electric_moped' |
  'blinds_closed' |
  'grid_goldenratio' |
  'attach_file_add' |
  'elderly_woman' |
  'lab_panel' |
  'carpenter' |
  'reset_wrench' |
  'file_copy' |
  'view_in_ar' |
  'stars' |
  'assignment' |
  'sound_detection_glass_break' |
  'groups' |
  'settings_input_svideo' |
  'play_for_work' |
  'medication' |
  'css' |
  'dishwasher_gen' |
  'deployed_code_update' |
  'cycle' |
  'home_pin' |
  'cyclone' |
  'immunology' |
  'merge_type' |
  'arrow_circle_up' |
  'hail' |
  'blender' |
  'dentistry' |
  'nest_wifi_pro_2' |
  'battery_alert' |
  'file_download_off' |
  'power_settings_new' |
  'download_for_offline' |
  'signal_cellular_connected_no_internet_4_bar' |
  'skateboarding' |
  'looks_5' |
  'settings_system_daydream' |
  'settings_panorama' |
  'bluetooth_connected' |
  'data_exploration' |
  'nest_eco_leaf' |
  'universal_currency_alt' |
  'security' |
  'nest_multi_room' |
  'stylus' |
  'manufacturing' |
  'post_add' |
  'skeleton' |
  'pen_size_2' |
  'more' |
  'alarm_off' |
  'lan' |
  'stay_current_portrait' |
  'search_check' |
  'insert_chart' |
  'museum' |
  'set_meal' |
  'signal_disconnected' |
  'speaker_notes' |
  'rate_review' |
  'specific_gravity' |
  'body_fat' |
  'note_alt' |
  'egg' |
  'spellcheck' |
  'ac_unit' |
  'face_5' |
  'shelf_position' |
  'video_label' |
  'align_horizontal_center' |
  'thumb_up' |
  'crop_rotate' |
  'temple_hindu' |
  'backlight_high' |
  'globe_asia' |
  'border_right' |
  'sentiment_excited' |
  'watch_off' |
  'php' |
  'glyphs' |
  'point_of_sale' |
  'location_home' |
  'video_library' |
  'sound_detection_dog_barking' |
  'media_bluetooth_off' |
  'settop_component' |
  'filter_9_plus' |
  'clock_loader_10' |
  'flare' |
  'nest_wifi_pro' |
  'align_space_around' |
  'single_bed' |
  'format_h2' |
  'climate_mini_split' |
  'attachment' |
  'snowing' |
  'print_connect' |
  'e_mobiledata' |
  'transfer_within_a_station' |
  'browse_activity' |
  'space_dashboard' |
  'sick' |
  'home_health' |
  'border_vertical' |
  'mic_off' |
  'roundabout_left' |
  'text_select_move_back_character' |
  'child_care' |
  'format_h3' |
  'unfold_more' |
  '1x_mobiledata' |
  'rainy' |
  'file_save' |
  'call_split' |
  'breaking_news_alt_1' |
  'bubbles' |
  'battery_horiz_000' |
  '3k_plus' |
  '9mp' |
  'directions_subway' |
  'transgender' |
  'summarize' |
  'water_drop' |
  'ungroup' |
  'align_start' |
  'web_stories' |
  'signal_cellular_0_bar' |
  'emergency_heat' |
  'chromecast_device' |
  'switch_right' |
  'microwave_gen' |
  'control_camera' |
  'repartition' |
  'shadow' |
  'face_4' |
  'filter_vintage' |
  'movie_info' |
  'arrow_downward_alt' |
  'no_food' |
  'shutter_speed' |
  'front_hand' |
  'select_check_box' |
  'explore_nearby' |
  'communities' |
  'format_textdirection_l_to_r' |
  'checklist_rtl' |
  'stacked_email' |
  'bluetooth_searching' |
  'format_underlined_squiggle' |
  'memory' |
  '17mp' |
  'pen_size_3' |
  'quiet_time_active' |
  'fit_width' |
  'bento' |
  'stairs' |
  'flash_off' |
  'tibia_alt' |
  'arrow_circle_down' |
  'contacts' |
  'pan_zoom' |
  'motion_sensor_idle' |
  'construction' |
  'accessible' |
  'format_letter_spacing' |
  'oral_disease' |
  'screenshot_monitor' |
  'water_lux' |
  'text_to_speech' |
  'preview_off' |
  'looks_4' |
  'pregnant_woman' |
  'sledding' |
  'flip_camera_android' |
  'keyboard_keys' |
  'mimo_disconnect' |
  'photo_camera' |
  'zone_person_idle' |
  'star' |
  'auto_towing' |
  'nutrition' |
  'humidity_indoor' |
  'format_list_bulleted' |
  'work_history' |
  'candlestick_chart' |
  'brand_awareness' |
  '30fps_select' |
  'navigate_next' |
  'crop_9_16' |
  'nest_wake_on_press' |
  'extension' |
  'attach_file_off' |
  'noise_control_on' |
  'file_save_off' |
  'public_off' |
  'no_meeting_room' |
  '7k' |
  'box_edit' |
  'mobile_friendly' |
  'discover_tune' |
  'arrow_back_ios' |
  'thumbs_up_down' |
  'web_traffic' |
  'checklist' |
  'hdr_weak' |
  'solar_power' |
  'account_circle_off' |
  'text_fields' |
  'water_bottle' |
  'tsunami' |
  'frame_person' |
  'transition_slide' |
  'flip_camera_ios' |
  'kitchen' |
  'visibility_off' |
  'interpreter_mode' |
  'cloud_circle' |
  'odt' |
  'remove_selection' |
  'background_replace' |
  'experiment' |
  'flight_class' |
  'engineering' |
  'motion_mode' |
  'splitscreen_add' |
  'rowing' |
  'star_rate_half' |
  'iron' |
  'radiology' |
  'problem' |
  'delete_history' |
  'edit' |
  'filter_alt' |
  'soap' |
  'garage_home' |
  'hdr_on_select' |
  'wheelchair_pickup' |
  'toggle_on' |
  'fullscreen_exit' |
  'format_list_numbered' |
  'wc' |
  'music_video' |
  'ramen_dining' |
  'lightning_stand' |
  'looks_6' |
  'auto_transmission' |
  'api' |
  'anchor' |
  'contactless' |
  'sleep_score' |
  'content_paste_search' |
  'air_purifier_gen' |
  'resize' |
  'kayaking' |
  'noise_aware' |
  'brightness_auto' |
  'local_see' |
  'floor_lamp' |
  'universal_local' |
  'web_asset_off' |
  'smart_screen' |
  'stack_off' |
  'pen_size_1' |
  'hardware' |
  'capture' |
  'airline_stops' |
  'brunch_dining' |
  'tonality' |
  'stay_primary_landscape' |
  'left_click' |
  'face_6' |
  'salinity' |
  'apk_document' |
  'pet_supplies' |
  'keyboard_arrow_right' |
  'media_bluetooth_on' |
  'camera_video' |
  'bottom_right_click' |
  '6_ft_apart' |
  'phone_disabled' |
  'total_dissolved_solids' |
  'beach_access' |
  'open_jam' |
  '50mp' |
  'no_meals' |
  'mark_email_read' |
  '15mp' |
  'dangerous' |
  'wallpaper_slideshow' |
  'edit_square' |
  'airline_seat_flat_angled' |
  'quick_reference' |
  'keyboard_double_arrow_up' |
  'nest_audio' |
  'bookmark_remove' |
  'dresser' |
  'airline_seat_legroom_extra' |
  'nearby_off' |
  'contactless_off' |
  'play_disabled' |
  'paragliding' |
  'precision_manufacturing' |
  'hdr_strong' |
  'vertical_shades_closed' |
  'sort_by_alpha' |
  'data_info_alert' |
  'lift_to_talk' |
  'format_h1' |
  'format_line_spacing' |
  'legend_toggle' |
  'align_justify_center' |
  'conversion_path_off' |
  'voice_selection' |
  'my_location' |
  'margin' |
  'finance_mode' |
  'topic' |
  'slow_motion_video' |
  'text_select_start' |
  'timer_10' |
  'vertical_align_top' |
  'water_medium' |
  'avg_pace' |
  'content_paste_off' |
  'shadow_minus' |
  'car_repair' |
  'content_paste' |
  'local_hospital' |
  'ifl' |
  'adjust' |
  'network_ping' |
  'restaurant_menu' |
  'emoji_nature' |
  'looks' |
  'ar_on_you' |
  'looks_one' |
  'oven_gen' |
  'settings_cell' |
  'equalizer' |
  'faucet' |
  'checked_bag' |
  'corporate_fare' |
  'reviews' |
  'keyboard_double_arrow_right' |
  'woman' |
  'clear_all' |
  'video_camera_front_off' |
  'format_align_justify' |
  'dinner_dining' |
  'gynecology' |
  'respiratory_rate' |
  'follow_the_signs' |
  'warehouse' |
  'room_service' |
  'verified_user' |
  'left_panel_close' |
  'switch_access_shortcut' |
  'living' |
  'filter_list' |
  'input' |
  'keyboard_off' |
  'lock_clock' |
  'auto_delete' |
  'universal_currency' |
  'settings_backup_restore' |
  'local_police' |
  'power_off' |
  'nest_remote' |
  'format_indent_decrease' |
  'nature_people' |
  'schema' |
  'sync_disabled' |
  'image_search' |
  'theaters' |
  'view_module' |
  'unsubscribe' |
  'patient_list' |
  'request_quote' |
  'border_style' |
  'settings_bluetooth' |
  'computer' |
  'developer_guide' |
  'electric_bolt' |
  'airport_shuttle' |
  'wash' |
  'lte_mobiledata' |
  'wb_shade' |
  'toys_fan' |
  'folder_data' |
  'south_east' |
  'do_not_touch' |
  'select' |
  'lte_mobiledata_badge' |
  'pacemaker' |
  'arming_countdown' |
  'graphic_eq' |
  'attach_file' |
  'sentiment_content' |
  'blur_on' |
  'deselect' |
  'language' |
  'person_celebrate' |
  'keyboard_voice' |
  'picture_in_picture_medium' |
  'heat_pump' |
  'pin_end' |
  'person_off' |
  'height' |
  'portable_wifi_off' |
  'highlight_mouse_cursor' |
  'water_full' |
  'foundation' |
  'meeting_room' |
  'analytics' |
  'magnify_fullscreen' |
  'golf_course' |
  'fitness_center' |
  'health_metrics' |
  'vignette' |
  'arrows_outward' |
  'egg_alt' |
  'infrared' |
  'contact_mail' |
  '3p' |
  'chalet' |
  'arrow_or_edge' |
  'phonelink_setup' |
  'sentiment_frustrated' |
  'edit_attributes' |
  'delete_forever' |
  'mitre' |
  'turn_slight_left' |
  'phone_callback' |
  'repeat_one_on' |
  'videogame_asset' |
  'assist_walker' |
  'hotel_class' |
  'local_convenience_store' |
  'texture' |
  'diamond' |
  'delete' |
  'farsight_digital' |
  'straight' |
  'table_restaurant' |
  'exercise' |
  'format_ink_highlighter' |
  'subdirectory_arrow_right' |
  'router' |
  'phone_bluetooth_speaker' |
  'select_window' |
  'motion_blur' |
  'body_system' |
  'no_backpack' |
  'arrow_upward_alt' |
  'wifi_1_bar' |
  'text_select_move_down' |
  'floor' |
  'icecream' |
  'done_all' |
  'open_in_phone' |
  'femur' |
  'view_agenda' |
  'line_end_arrow_notch' |
  'imagesmode' |
  'lens_blur' |
  'g_translate' |
  'add_reaction' |
  'no_sim' |
  'swipe_up' |
  'app_blocking' |
  'pivot_table_chart' |
  'sticky_note_2' |
  'bath_public_large' |
  'theater_comedy' |
  'document_scanner' |
  '12mp' |
  'family_home' |
  'sync_alt' |
  'sync' |
  'wall_lamp' |
  'two_wheeler' |
  'call' |
  'psychology_alt' |
  'magnify_docked' |
  'right_click' |
  '4k_plus' |
  'rotate_right' |
  'waves' |
  'calendar_clock' |
  'ios' |
  'social_distance' |
  'pause_presentation' |
  'person_remove' |
  'cloud_off' |
  'clock_loader_60' |
  'account_child' |
  'web' |
  'blur_short' |
  'settings_timelapse' |
  'group_remove' |
  'finance_chip' |
  'fire_extinguisher' |
  'podium' |
  'short_text' |
  'detector_smoke' |
  'sports_score' |
  'signal_wifi_statusbar_null' |
  'reorder' |
  'file_present' |
  'nest_true_radiant' |
  '60fps_select' |
  'speed_1_5' |
  'remove_done' |
  'align_flex_center' |
  'sentiment_neutral' |
  'bedtime_off' |
  'settings_alert' |
  'mobiledata_off' |
  'format_size' |
  'open_in_new_down' |
  'delete_sweep' |
  '30fps' |
  'photo_prints' |
  'settings_overscan' |
  'pill' |
  'clarify' |
  'waterfall_chart' |
  'flood' |
  'jump_to_element' |
  'checkbook' |
  'grouped_bar_chart' |
  'masks' |
  'cheer' |
  'chat_error' |
  'wifi_protected_setup' |
  'trail_length' |
  'browser_updated' |
  'minor_crash' |
  'texture_minus' |
  'tv_remote' |
  'article_shortcut' |
  'dropdown' |
  'brightness_1' |
  'signal_cellular_null' |
  'enhanced_encryption' |
  'mode_cool_off' |
  'azm' |
  'h_mobiledata' |
  'toc' |
  'developer_board_off' |
  'rubric' |
  'sd_card_alert' |
  'outpatient' |
  'avg_time' |
  'add_a_photo' |
  'closed_caption_disabled' |
  'nature' |
  'align_space_even' |
  'panorama_photosphere' |
  'scoreboard' |
  'hard_drive_2' |
  'fluid' |
  'artist' |
  'add_home_work' |
  'swipe_left_alt' |
  'cleaning_services' |
  'physical_therapy' |
  'airlines' |
  'window_sensor' |
  'featured_play_list' |
  'home_storage' |
  'assured_workload' |
  'grain' |
  'roller_shades' |
  'hourglass_empty' |
  'ev_mobiledata_badge' |
  'chair_alt' |
  'queue_play_next' |
  'swipe_down' |
  'cleaning_bucket' |
  'share' |
  'edgesensor_low' |
  '10k' |
  'signal_cellular_2_bar' |
  'add_box' |
  'wifi_off' |
  'manga' |
  'person_2' |
  'rule_settings' |
  'personal_injury' |
  'album' |
  'vpn_lock' |
  'qr_code' |
  'g_mobiledata' |
  'hd' |
  'burst_mode' |
  'money' |
  'swipe_down_alt' |
  'mail_lock' |
  'horizontal_split' |
  'align_items_stretch' |
  'align_center' |
  'productivity' |
  'imagesearch_roller' |
  'location_away' |
  'schedule' |
  'language_korean_latin' |
  'autorenew' |
  'bedroom_parent' |
  'subway' |
  'team_dashboard' |
  'hide_image' |
  'thread_unread' |
  'not_started' |
  'update_disabled' |
  'do_not_disturb_on_total_silence' |
  'temple_buddhist' |
  'sort' |
  'text_fields_alt' |
  'sip' |
  'flex_wrap' |
  'storage' |
  'electrical_services' |
  'folder_open' |
  'gesture_select' |
  'table_bar' |
  'settings_brightness' |
  'image_aspect_ratio' |
  'remove' |
  'psychiatry' |
  'pageview' |
  'explicit' |
  'brightness_3' |
  'traffic' |
  '3g_mobiledata' |
  'undo' |
  'splitscreen_bottom' |
  'south_america' |
  'switch_access_shortcut_add' |
  'cancel_presentation' |
  'shadow_add' |
  'stack' |
  'personal_bag' |
  'sports_bar' |
  'tablet_android' |
  'robot' |
  'data_alert' |
  'ev_shadow_minus' |
  'work_alert' |
  'event_seat' |
  'shutter_speed_minus' |
  'flashlight_off' |
  'south_west' |
  'sd_card' |
  'h_plus_mobiledata' |
  'bid_landscape_disabled' |
  'connected_tv' |
  'replay_10' |
  'u_turn_left' |
  'music_cast' |
  'description' |
  'filter' |
  'general_device' |
  'bottom_navigation' |
  'allergies' |
  'water' |
  'thermostat_auto' |
  'drag_click' |
  'pageless' |
  'tab_group' |
  'contact_support' |
  'rocket_launch' |
  'call_quality' |
  'align_flex_end' |
  'back_hand' |
  'switch' |
  'cast_connected' |
  '9k_plus' |
  'charger' |
  'rule_folder' |
  'heart_broken' |
  'person_pin' |
  'text_rotate_up' |
  'rebase_edit' |
  'note_stack_add' |
  'handshake' |
  'airline_seat_recline_normal' |
  'data_object' |
  'price_check' |
  'ios_share' |
  'text_select_move_forward_word' |
  'comment' |
  'directions_off' |
  'heart_minus' |
  'timeline' |
  'electric_bike' |
  'mintmark' |
  'inactive_order' |
  'check_box' |
  'mode_of_travel' |
  'settings_b_roll' |
  'pinch' |
  'border_bottom' |
  'broadcast_on_home' |
  'no_adult_content' |
  'settings_power' |
  'output' |
  'screen_rotation_up' |
  'globe' |
  'stop_screen_share' |
  'credit_card_off' |
  'event_note' |
  'network_check' |
  'blood_pressure' |
  'route' |
  'nordic_walking' |
  'assignment_late' |
  'unknown_med' |
  'toys_and_games' |
  'reply_all' |
  'unfold_less' |
  'tune' |
  'fork_right' |
  'payments' |
  'linked_camera' |
  'nest_wifi_router' |
  'signal_cellular_alt_1_bar' |
  'ad_group' |
  'wifi_home' |
  'trip' |
  'pets' |
  'align_justify_space_between' |
  'dishwasher' |
  'water_heater' |
  '10mp' |
  'e_mobiledata_badge' |
  'switch_account' |
  'mood_bad' |
  'stacked_bar_chart' |
  'steppers' |
  'grid_3x3' |
  'person_alert' |
  'text_select_move_back_word' |
  'weekend' |
  'communication' |
  'add_alert' |
  'call_merge' |
  'html' |
  'brightness_2' |
  'add_to_queue' |
  'perm_phone_msg' |
  'edgesensor_high' |
  'battery_5_bar' |
  'width_full' |
  'hourglass_bottom' |
  'insert_page_break' |
  'scanner' |
  'add_circle' |
  'notifications' |
  'position_bottom_left' |
  'featured_video' |
  'room_preferences' |
  'atr' |
  'view_column_2' |
  'pinch_zoom_out' |
  'filter_list_off' |
  'maps_ugc' |
  'add_to_photos' |
  'interests' |
  'snippet_folder' |
  'code_off' |
  'data_array' |
  'checked_bag_question' |
  'connect_without_contact' |
  'developer_mode_tv' |
  'auto_read_play' |
  'screen_share' |
  'join_left' |
  'vr180_create2d_off' |
  'lists' |
  'local_parking' |
  'no_stroller' |
  'cut' |
  'view_sidebar' |
  'dermatology' |
  'align_horizontal_left' |
  'person_3' |
  'draft_orders' |
  'forms_apps_script' |
  'cloud' |
  'door_open' |
  '14mp' |
  'tty' |
  'wifi_calling_1' |
  'report_off' |
  'king_bed' |
  'folder_copy' |
  'add_comment' |
  'license' |
  'signal_wifi_bad' |
  'shuffle' |
  'partner_reports' |
  'stacked_inbox' |
  'picture_in_picture_off' |
  'flash_auto' |
  'window' |
  'error' |
  'compass_calibration' |
  'not_accessible' |
  'devices_off' |
  'snowboarding' |
  'things_to_do' |
  'date_range' |
  'control_point_duplicate' |
  'lock_person' |
  'stat_minus_3' |
  'balance' |
  'chair' |
  'airline_seat_legroom_reduced' |
  'sunny' |
  'align_horizontal_right' |
  'no_transfer' |
  'format_overline' |
  'view_in_ar_off' |
  'edit_document' |
  'swipe_right' |
  'scuba_diving' |
  'speech_to_text' |
  'motorcycle' |
  'line_start_diamond' |
  'format_bold' |
  'language_chinese_dayi' |
  'tools_flat_head' |
  'upload' |
  'drag_handle' |
  'transition_push' |
  'sword_rose' |
  'sensor_door' |
  'full_coverage' |
  'phone_paused' |
  'brightness_6' |
  'pause' |
  'add_to_home_screen' |
  'format_shapes' |
  'arrow_forward' |
  'view_week' |
  'draw_collage' |
  'e911_avatar' |
  'domain_disabled' |
  'flip_to_back' |
  'exposure' |
  'encrypted' |
  'fertile' |
  'notification_multiple' |
  'print_add' |
  'water_voc' |
  'no_sound' |
  'business_chip' |
  'lda' |
  'next_week' |
  'forward' |
  'flip' |
  'format_clear' |
  'swipe_right_alt' |
  'speed_1_2' |
  'motion_sensor_active' |
  'bookmark' |
  'sweep' |
  'mic_external_on' |
  'ink_marker' |
  'help' |
  'rocket' |
  'camera_indoor' |
  'watch_wake' |
  'battery_full' |
  'font_download_off' |
  'sports_motorsports' |
  'fact_check' |
  'asterisk' |
  'nest_remote_comfort_sensor' |
  'add_photo_alternate' |
  'match_word' |
  'music_note' |
  'more_vert' |
  'detector_offline' |
  'flutter_dash' |
  'airware' |
  'transit_enterexit' |
  'settings_applications' |
  'real_estate_agent' |
  'safety_check_off' |
  'water_do' |
  'tablet' |
  'wrist' |
  'clear_day' |
  'takeout_dining' |
  'clinical_notes' |
  'flex_no_wrap' |
  'mode_standby' |
  'line_start_square' |
  'nest_cam_iq_outdoor' |
  'slideshow' |
  'currency_bitcoin' |
  'stay_primary_portrait' |
  'tools_pliers_wire_stripper' |
  'sim_card_download' |
  'tools_ladder' |
  'webhook' |
  'laundry' |
  'chart_data' |
  'elevator' |
  'snowmobile' |
  'dry_cleaning' |
  'score' |
  'matter' |
  'dialogs' |
  'notifications_unread' |
  'business_messages' |
  'chrome_reader_mode' |
  'wifi_tethering_error' |
  'done' |
  'scrollable_header' |
  'batch_prediction' |
  'format_color_fill' |
  'square_foot' |
  'moving_beds' |
  'calendar_view_week' |
  'manage_accounts' |
  'houseboat' |
  'coronavirus' |
  'airline_seat_legroom_normal' |
  'contract_edit' |
  'not_listed_location' |
  'text_rotation_none' |
  'transition_dissolve' |
  'tablet_mac' |
  'hive' |
  'wifi_channel' |
  'grocery' |
  'alt_route' |
  'voice_over_off' |
  'camera_front' |
  'forward_30' |
  'editor_choice' |
  'weather_hail' |
  'check_small' |
  'not_accessible_forward' |
  'brightness_7' |
  'no_luggage' |
  'mop' |
  '4g_mobiledata' |
  'sync_problem' |
  'all_match' |
  'menu' |
  'align_stretch' |
  'hdr_auto_select' |
  'align_justify_space_even' |
  'skillet_cooktop' |
  'expand_less' |
  '2k_plus' |
  'psychology' |
  'shield_with_house' |
  'swipe_vertical' |
  'play_arrow' |
  'backspace' |
  '2d' |
  'nest_clock_farsight_analog' |
  'dynamic_feed' |
  'keyboard_tab' |
  'routine' |
  'u_turn_right' |
  'format_paint' |
  'download_2' |
  'stat_minus_2' |
  'raven' |
  'pip_exit' |
  'merge' |
  'box_add' |
  'dashboard_customize' |
  'weather_snowy' |
  'assignment_returned' |
  'flowsheet' |
  'signal_cellular_pause' |
  'web_asset' |
  'password' |
  'procedure' |
  'flatware' |
  '123' |
  'high_quality' |
  'add_chart' |
  'battery_4_bar' |
  'spa' |
  'published_with_changes' |
  'clean_hands' |
  'border_color' |
  'wifi_calling_2' |
  'sports_gymnastics' |
  'nest_heat_link_e' |
  'electric_scooter' |
  'mouse' |
  'output_circle' |
  'pentagon' |
  'jamboard_kiosk' |
  'eyeglasses' |
  'person_4' |
  'female' |
  'aod_tablet' |
  'radio_button_checked' |
  'block' |
  'battery_unknown' |
  'kettle' |
  'multiple_stop' |
  'photo_library' |
  'pergola' |
  'location_on' |
  'view_column' |
  'person_add' |
  'orthopedics' |
  'offline_pin' |
  'filter_8' |
  'phishing' |
  'network_intelligence_update' |
  'admin_meds' |
  'zoom_out' |
  'fiber_new' |
  'shield_locked' |
  'data_saver_on' |
  'send_time_extension' |
  'urology' |
  'deck' |
  'man' |
  'prescriptions' |
  'hourglass_disabled' |
  'settings_photo_camera' |
  'window_closed' |
  'plumbing' |
  'stack_star' |
  'valve' |
  'digital_out_of_home' |
  'streetview' |
  'timer_10_alt_1' |
  'vibration' |
  'motion_sensor_alert' |
  'battery_low' |
  'grass' |
  'phonelink_ring' |
  'share_reviews' |
  'biotech' |
  'brightness_5' |
  'vaccines' |
  'battery_charging_full' |
  'security_update_warning' |
  'range_hood' |
  'hdr_off' |
  'grid_off' |
  'celebration' |
  'arrow_back_ios_new' |
  'history' |
  'switch_video' |
  'arrow_forward_ios' |
  'cards' |
  'gavel' |
  'folder' |
  'conversion_path' |
  'heat' |
  'alarm' |
  'speaker_group' |
  'language_chinese_quick' |
  'home_improvement_and_tools' |
  'language_chinese_pinyin' |
  'star_rate' |
  'in_home_mode' |
  'local_bar' |
  'group_work' |
  'currency_yen' |
  'input_circle' |
  'eco' |
  'night_shelter' |
  'gif_box' |
  'open_with' |
  'tab_new_right' |
  'stroke_partial' |
  'line_end' |
  'contrast_rtl_off' |
  'vertical_align_bottom' |
  'gastroenterology' |
  'fingerprint' |
  'synagogue' |
  'breastfeeding' |
  'electric_meter' |
  'signal_wifi_4_bar' |
  'download_done' |
  'battery_horiz_075' |
  'counter_9' |
  'laptop_windows' |
  'emoji_people' |
  'cake_add' |
  'timer' |
  'regular_expression' |
  'gamepad' |
  'cached' |
  'monitor' |
  'music_off' |
  'file_copy_off' |
  'settings_input_component' |
  'emergency_share' |
  'radio_button_unchecked' |
  'vr180_create2d' |
  'devices_other' |
  'feature_search' |
  'settings_account_box' |
  'screenshot_tablet' |
  'multiline_chart' |
  'dual_screen' |
  'all_out' |
  'counter_8' |
  'detector_alarm' |
  'travel_luggage_and_bags' |
  'align_vertical_top' |
  'keyboard_double_arrow_down' |
  'nearby_error' |
  'timer_3' |
  'photo' |
  'incomplete_circle' |
  'notification_add' |
  'print' |
  'lte_plus_mobiledata' |
  'border_top' |
  'light' |
  'volunteer_activism' |
  'unarchive' |
  'exclamation' |
  'weight' |
  'pin_drop' |
  'open_in_new' |
  'shopping_basket' |
  'thermostat' |
  'format_letter_spacing_standard' |
  'qr_code_scanner' |
  'mic_external_off' |
  'credit_card_gear' |
  'arrow_insert' |
  'move_location' |
  'propane' |
  'cable' |
  'airline_seat_flat' |
  'accessibility' |
  'humidity_percentage' |
  'door_back' |
  'mfg_nest_yale_lock' |
  'call_end' |
  'thumbnail_bar' |
  'forward_media' |
  'mobile_off' |
  'emoji_symbols' |
  'wifi_tethering_off' |
  'variable_add' |
  'home_iot_device' |
  'water_ph' |
  'sanitizer' |
  'brightness_4' |
  'ssid_chart' |
  'security_update_good' |
  'share_windows' |
  'star_half' |
  'light_group' |
  'print_error' |
  'new_releases' |
  'crossword' |
  'elderly' |
  'radio_button_partial' |
  'gpp_bad' |
  'signal_cellular_3_bar' |
  'private_connectivity' |
  'align_vertical_bottom' |
  '16mp' |
  'ad_group_off' |
  'blanket' |
  'upgrade' |
  'loyalty' |
  'podiatry' |
  'nest_thermostat_sensor_eu' |
  'source_notes' |
  'fork_left' |
  'smoking_rooms' |
  'filter_9' |
  'vpn_key' |
  'attractions' |
  'add_notes' |
  'trail_length_medium' |
  'keyboard_tab_rtl' |
  'scan_delete' |
  '1k' |
  'escalator' |
  'wifi_add' |
  'stat_minus_1' |
  'privacy' |
  'outdoor_garden' |
  'read_more' |
  'fluorescent' |
  'key_vertical' |
  'special_character' |
  '8mp' |
  'foggy' |
  'wifi_calling_3' |
  'emoji_transportation' |
  'waving_hand' |
  'keyboard_capslock' |
  'pin_invoke' |
  'cleaning';
