#!/bin/bash
#
# graylog2-web-interface:   graylog2 web interface
#
# chkconfig: - 98 02
# description:  Starts graylog2-web-interface using passenger-standalone.
#
# config
USER=graylog
APP_DIR=/opt/graylog2/graylog2-web-interface/
ADDR=0.0.0.0
PORT=3000
ENVIRONMENT=production
LOG_FILE=/var/log/graylog2-web-interface.log
export HOME="/root"
 
. /lib/lsb/init-functions
case "$1" in
  start)
    echo "Starting graylog2-web-interface"
    cd $APP_DIR; passenger start -d -a $ADDR -p $PORT -e $ENVIRONMENT --user $USER
    ;;
  stop)
    echo "Stopping graylog2-web-interface"
    cd $APP_DIR; passenger stop -p $PORT
    ;;
  status)
    cd $APP_DIR; passenger status -p $PORT
   ;;
  *)
    echo "Usage: $0 start|stop|status" >&2
    exit 3
    ;;
esac
