#!/bin/sh
#
# graylog2-server:   graylog2 message collector
#
# chkconfig: - 98 02
# description:  This daemon listens for syslog and GELF messages and stores them in mongodb
#

CMD=$1
NOHUP=`which nohup`
JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::")
JAVA_CMD=$JAVA_HOME/bin/java

GRAYLOG2_SERVER_HOME=/opt/graylog2/graylog2-server

start() {
    echo "Starting graylog2-server ..."
    $NOHUP $JAVA_CMD -jar $GRAYLOG2_SERVER_HOME/graylog2-server.jar > /var/log/graylog2.log 2>&1 &
}

stop() {
        PID=`cat /tmp/graylog2.pid`
        echo "Stopping graylog2-server ($PID) ..."
        kill $PID
}

restart() {
    echo "Restarting graylog2-server ..."
        stop
        start
}

case "$CMD" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage $0 {start|stop|restart}"
        RETVAL=1
esac
