/*
 * Copyright (C) 2020 Graylog, Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the Server Side Public License, version 1,
 * as published by MongoDB, Inc.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * Server Side Public License for more details.
 *
 * You should have received a copy of the Server Side Public License
 * along with this program. If not, see
 * <http://www.mongodb.com/licensing/server-side-public-license>.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/netflow_v9.proto
// Protobuf Java Version: 4.26.0

package org.graylog.plugins.netflow.v9;

public final class NetFlowV9Journal {
  private NetFlowV9Journal() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 0,
      /* suffix= */ "",
      NetFlowV9Journal.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RawNetflowV9OrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.graylog.plugins.netflow.v9.RawNetflowV9)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * all applicable templates that are referenced by the packets
     * </pre>
     *
     * <code>map&lt;uint32, bytes&gt; templates = 1;</code>
     */
    int getTemplatesCount();
    /**
     * <pre>
     * all applicable templates that are referenced by the packets
     * </pre>
     *
     * <code>map&lt;uint32, bytes&gt; templates = 1;</code>
     */
    boolean containsTemplates(
        int key);
    /**
     * Use {@link #getTemplatesMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, com.google.protobuf.ByteString>
    getTemplates();
    /**
     * <pre>
     * all applicable templates that are referenced by the packets
     * </pre>
     *
     * <code>map&lt;uint32, bytes&gt; templates = 1;</code>
     */
    java.util.Map<java.lang.Integer, com.google.protobuf.ByteString>
    getTemplatesMap();
    /**
     * <pre>
     * all applicable templates that are referenced by the packets
     * </pre>
     *
     * <code>map&lt;uint32, bytes&gt; templates = 1;</code>
     */
    /* nullable */
com.google.protobuf.ByteString getTemplatesOrDefault(
        int key,
        /* nullable */
com.google.protobuf.ByteString defaultValue);
    /**
     * <pre>
     * all applicable templates that are referenced by the packets
     * </pre>
     *
     * <code>map&lt;uint32, bytes&gt; templates = 1;</code>
     */
    com.google.protobuf.ByteString getTemplatesOrThrow(
        int key);

    /**
     * <pre>
     * there is only one option template, but we need to know its template id, so a map is the easiest way to find it
     * </pre>
     *
     * <code>map&lt;uint32, bytes&gt; optionTemplate = 2;</code>
     */
    int getOptionTemplateCount();
    /**
     * <pre>
     * there is only one option template, but we need to know its template id, so a map is the easiest way to find it
     * </pre>
     *
     * <code>map&lt;uint32, bytes&gt; optionTemplate = 2;</code>
     */
    boolean containsOptionTemplate(
        int key);
    /**
     * Use {@link #getOptionTemplateMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, com.google.protobuf.ByteString>
    getOptionTemplate();
    /**
     * <pre>
     * there is only one option template, but we need to know its template id, so a map is the easiest way to find it
     * </pre>
     *
     * <code>map&lt;uint32, bytes&gt; optionTemplate = 2;</code>
     */
    java.util.Map<java.lang.Integer, com.google.protobuf.ByteString>
    getOptionTemplateMap();
    /**
     * <pre>
     * there is only one option template, but we need to know its template id, so a map is the easiest way to find it
     * </pre>
     *
     * <code>map&lt;uint32, bytes&gt; optionTemplate = 2;</code>
     */
    /* nullable */
com.google.protobuf.ByteString getOptionTemplateOrDefault(
        int key,
        /* nullable */
com.google.protobuf.ByteString defaultValue);
    /**
     * <pre>
     * there is only one option template, but we need to know its template id, so a map is the easiest way to find it
     * </pre>
     *
     * <code>map&lt;uint32, bytes&gt; optionTemplate = 2;</code>
     */
    com.google.protobuf.ByteString getOptionTemplateOrThrow(
        int key);

    /**
     * <pre>
     * the raw packets as received. it might contain templates as well, but even if it does the above fields will have that information, too
     * in case we previously buffered flows, this may contain more than one flow. in situations when we have all templates already
     * this will be a single packet sent by the exporter
     * </pre>
     *
     * <code>repeated bytes packets = 3;</code>
     * @return A list containing the packets.
     */
    java.util.List<com.google.protobuf.ByteString> getPacketsList();
    /**
     * <pre>
     * the raw packets as received. it might contain templates as well, but even if it does the above fields will have that information, too
     * in case we previously buffered flows, this may contain more than one flow. in situations when we have all templates already
     * this will be a single packet sent by the exporter
     * </pre>
     *
     * <code>repeated bytes packets = 3;</code>
     * @return The count of packets.
     */
    int getPacketsCount();
    /**
     * <pre>
     * the raw packets as received. it might contain templates as well, but even if it does the above fields will have that information, too
     * in case we previously buffered flows, this may contain more than one flow. in situations when we have all templates already
     * this will be a single packet sent by the exporter
     * </pre>
     *
     * <code>repeated bytes packets = 3;</code>
     * @param index The index of the element to return.
     * @return The packets at the given index.
     */
    com.google.protobuf.ByteString getPackets(int index);
  }
  /**
   * Protobuf type {@code org.graylog.plugins.netflow.v9.RawNetflowV9}
   */
  public static final class RawNetflowV9 extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.graylog.plugins.netflow.v9.RawNetflowV9)
      RawNetflowV9OrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 0,
        /* suffix= */ "",
        RawNetflowV9.class.getName());
    }
    // Use RawNetflowV9.newBuilder() to construct.
    private RawNetflowV9(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private RawNetflowV9() {
      packets_ = emptyList(com.google.protobuf.ByteString.class);
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.graylog.plugins.netflow.v9.NetFlowV9Journal.internal_static_org_graylog_plugins_netflow_v9_RawNetflowV9_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetTemplates();
        case 2:
          return internalGetOptionTemplate();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.graylog.plugins.netflow.v9.NetFlowV9Journal.internal_static_org_graylog_plugins_netflow_v9_RawNetflowV9_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.graylog.plugins.netflow.v9.NetFlowV9Journal.RawNetflowV9.class, org.graylog.plugins.netflow.v9.NetFlowV9Journal.RawNetflowV9.Builder.class);
    }

    public static final int TEMPLATES_FIELD_NUMBER = 1;
    private static final class TemplatesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, com.google.protobuf.ByteString> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, com.google.protobuf.ByteString>newDefaultInstance(
                  org.graylog.plugins.netflow.v9.NetFlowV9Journal.internal_static_org_graylog_plugins_netflow_v9_RawNetflowV9_TemplatesEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.UINT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.BYTES,
                  com.google.protobuf.ByteString.EMPTY);
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.Integer, com.google.protobuf.ByteString> templates_;
    private com.google.protobuf.MapField<java.lang.Integer, com.google.protobuf.ByteString>
    internalGetTemplates() {
      if (templates_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            TemplatesDefaultEntryHolder.defaultEntry);
      }
      return templates_;
    }
    public int getTemplatesCount() {
      return internalGetTemplates().getMap().size();
    }
    /**
     * <pre>
     * all applicable templates that are referenced by the packets
     * </pre>
     *
     * <code>map&lt;uint32, bytes&gt; templates = 1;</code>
     */
    @java.lang.Override
    public boolean containsTemplates(
        int key) {

      return internalGetTemplates().getMap().containsKey(key);
    }
    /**
     * Use {@link #getTemplatesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, com.google.protobuf.ByteString> getTemplates() {
      return getTemplatesMap();
    }
    /**
     * <pre>
     * all applicable templates that are referenced by the packets
     * </pre>
     *
     * <code>map&lt;uint32, bytes&gt; templates = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.Integer, com.google.protobuf.ByteString> getTemplatesMap() {
      return internalGetTemplates().getMap();
    }
    /**
     * <pre>
     * all applicable templates that are referenced by the packets
     * </pre>
     *
     * <code>map&lt;uint32, bytes&gt; templates = 1;</code>
     */
    @java.lang.Override
    public /* nullable */
com.google.protobuf.ByteString getTemplatesOrDefault(
        int key,
        /* nullable */
com.google.protobuf.ByteString defaultValue) {

      java.util.Map<java.lang.Integer, com.google.protobuf.ByteString> map =
          internalGetTemplates().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * all applicable templates that are referenced by the packets
     * </pre>
     *
     * <code>map&lt;uint32, bytes&gt; templates = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getTemplatesOrThrow(
        int key) {

      java.util.Map<java.lang.Integer, com.google.protobuf.ByteString> map =
          internalGetTemplates().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int OPTIONTEMPLATE_FIELD_NUMBER = 2;
    private static final class OptionTemplateDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, com.google.protobuf.ByteString> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, com.google.protobuf.ByteString>newDefaultInstance(
                  org.graylog.plugins.netflow.v9.NetFlowV9Journal.internal_static_org_graylog_plugins_netflow_v9_RawNetflowV9_OptionTemplateEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.UINT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.BYTES,
                  com.google.protobuf.ByteString.EMPTY);
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.Integer, com.google.protobuf.ByteString> optionTemplate_;
    private com.google.protobuf.MapField<java.lang.Integer, com.google.protobuf.ByteString>
    internalGetOptionTemplate() {
      if (optionTemplate_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            OptionTemplateDefaultEntryHolder.defaultEntry);
      }
      return optionTemplate_;
    }
    public int getOptionTemplateCount() {
      return internalGetOptionTemplate().getMap().size();
    }
    /**
     * <pre>
     * there is only one option template, but we need to know its template id, so a map is the easiest way to find it
     * </pre>
     *
     * <code>map&lt;uint32, bytes&gt; optionTemplate = 2;</code>
     */
    @java.lang.Override
    public boolean containsOptionTemplate(
        int key) {

      return internalGetOptionTemplate().getMap().containsKey(key);
    }
    /**
     * Use {@link #getOptionTemplateMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, com.google.protobuf.ByteString> getOptionTemplate() {
      return getOptionTemplateMap();
    }
    /**
     * <pre>
     * there is only one option template, but we need to know its template id, so a map is the easiest way to find it
     * </pre>
     *
     * <code>map&lt;uint32, bytes&gt; optionTemplate = 2;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.Integer, com.google.protobuf.ByteString> getOptionTemplateMap() {
      return internalGetOptionTemplate().getMap();
    }
    /**
     * <pre>
     * there is only one option template, but we need to know its template id, so a map is the easiest way to find it
     * </pre>
     *
     * <code>map&lt;uint32, bytes&gt; optionTemplate = 2;</code>
     */
    @java.lang.Override
    public /* nullable */
com.google.protobuf.ByteString getOptionTemplateOrDefault(
        int key,
        /* nullable */
com.google.protobuf.ByteString defaultValue) {

      java.util.Map<java.lang.Integer, com.google.protobuf.ByteString> map =
          internalGetOptionTemplate().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * there is only one option template, but we need to know its template id, so a map is the easiest way to find it
     * </pre>
     *
     * <code>map&lt;uint32, bytes&gt; optionTemplate = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getOptionTemplateOrThrow(
        int key) {

      java.util.Map<java.lang.Integer, com.google.protobuf.ByteString> map =
          internalGetOptionTemplate().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int PACKETS_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> packets_ =
        emptyList(com.google.protobuf.ByteString.class);
    /**
     * <pre>
     * the raw packets as received. it might contain templates as well, but even if it does the above fields will have that information, too
     * in case we previously buffered flows, this may contain more than one flow. in situations when we have all templates already
     * this will be a single packet sent by the exporter
     * </pre>
     *
     * <code>repeated bytes packets = 3;</code>
     * @return A list containing the packets.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getPacketsList() {
      return packets_;
    }
    /**
     * <pre>
     * the raw packets as received. it might contain templates as well, but even if it does the above fields will have that information, too
     * in case we previously buffered flows, this may contain more than one flow. in situations when we have all templates already
     * this will be a single packet sent by the exporter
     * </pre>
     *
     * <code>repeated bytes packets = 3;</code>
     * @return The count of packets.
     */
    public int getPacketsCount() {
      return packets_.size();
    }
    /**
     * <pre>
     * the raw packets as received. it might contain templates as well, but even if it does the above fields will have that information, too
     * in case we previously buffered flows, this may contain more than one flow. in situations when we have all templates already
     * this will be a single packet sent by the exporter
     * </pre>
     *
     * <code>repeated bytes packets = 3;</code>
     * @param index The index of the element to return.
     * @return The packets at the given index.
     */
    public com.google.protobuf.ByteString getPackets(int index) {
      return packets_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessage
        .serializeIntegerMapTo(
          output,
          internalGetTemplates(),
          TemplatesDefaultEntryHolder.defaultEntry,
          1);
      com.google.protobuf.GeneratedMessage
        .serializeIntegerMapTo(
          output,
          internalGetOptionTemplate(),
          OptionTemplateDefaultEntryHolder.defaultEntry,
          2);
      for (int i = 0; i < packets_.size(); i++) {
        output.writeBytes(3, packets_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.Integer, com.google.protobuf.ByteString> entry
           : internalGetTemplates().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, com.google.protobuf.ByteString>
        templates__ = TemplatesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, templates__);
      }
      for (java.util.Map.Entry<java.lang.Integer, com.google.protobuf.ByteString> entry
           : internalGetOptionTemplate().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, com.google.protobuf.ByteString>
        optionTemplate__ = OptionTemplateDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, optionTemplate__);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < packets_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(packets_.get(i));
        }
        size += dataSize;
        size += 1 * getPacketsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.graylog.plugins.netflow.v9.NetFlowV9Journal.RawNetflowV9)) {
        return super.equals(obj);
      }
      org.graylog.plugins.netflow.v9.NetFlowV9Journal.RawNetflowV9 other = (org.graylog.plugins.netflow.v9.NetFlowV9Journal.RawNetflowV9) obj;

      if (!internalGetTemplates().equals(
          other.internalGetTemplates())) return false;
      if (!internalGetOptionTemplate().equals(
          other.internalGetOptionTemplate())) return false;
      if (!getPacketsList()
          .equals(other.getPacketsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetTemplates().getMap().isEmpty()) {
        hash = (37 * hash) + TEMPLATES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetTemplates().hashCode();
      }
      if (!internalGetOptionTemplate().getMap().isEmpty()) {
        hash = (37 * hash) + OPTIONTEMPLATE_FIELD_NUMBER;
        hash = (53 * hash) + internalGetOptionTemplate().hashCode();
      }
      if (getPacketsCount() > 0) {
        hash = (37 * hash) + PACKETS_FIELD_NUMBER;
        hash = (53 * hash) + getPacketsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.graylog.plugins.netflow.v9.NetFlowV9Journal.RawNetflowV9 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.graylog.plugins.netflow.v9.NetFlowV9Journal.RawNetflowV9 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.graylog.plugins.netflow.v9.NetFlowV9Journal.RawNetflowV9 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.graylog.plugins.netflow.v9.NetFlowV9Journal.RawNetflowV9 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.graylog.plugins.netflow.v9.NetFlowV9Journal.RawNetflowV9 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.graylog.plugins.netflow.v9.NetFlowV9Journal.RawNetflowV9 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.graylog.plugins.netflow.v9.NetFlowV9Journal.RawNetflowV9 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.graylog.plugins.netflow.v9.NetFlowV9Journal.RawNetflowV9 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.graylog.plugins.netflow.v9.NetFlowV9Journal.RawNetflowV9 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.graylog.plugins.netflow.v9.NetFlowV9Journal.RawNetflowV9 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.graylog.plugins.netflow.v9.NetFlowV9Journal.RawNetflowV9 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.graylog.plugins.netflow.v9.NetFlowV9Journal.RawNetflowV9 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.graylog.plugins.netflow.v9.NetFlowV9Journal.RawNetflowV9 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.graylog.plugins.netflow.v9.RawNetflowV9}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.graylog.plugins.netflow.v9.RawNetflowV9)
        org.graylog.plugins.netflow.v9.NetFlowV9Journal.RawNetflowV9OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.graylog.plugins.netflow.v9.NetFlowV9Journal.internal_static_org_graylog_plugins_netflow_v9_RawNetflowV9_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
          int number) {
        switch (number) {
          case 1:
            return internalGetTemplates();
          case 2:
            return internalGetOptionTemplate();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableTemplates();
          case 2:
            return internalGetMutableOptionTemplate();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.graylog.plugins.netflow.v9.NetFlowV9Journal.internal_static_org_graylog_plugins_netflow_v9_RawNetflowV9_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.graylog.plugins.netflow.v9.NetFlowV9Journal.RawNetflowV9.class, org.graylog.plugins.netflow.v9.NetFlowV9Journal.RawNetflowV9.Builder.class);
      }

      // Construct using org.graylog.plugins.netflow.v9.NetFlowV9Journal.RawNetflowV9.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        internalGetMutableTemplates().clear();
        internalGetMutableOptionTemplate().clear();
        packets_ = emptyList(com.google.protobuf.ByteString.class);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.graylog.plugins.netflow.v9.NetFlowV9Journal.internal_static_org_graylog_plugins_netflow_v9_RawNetflowV9_descriptor;
      }

      @java.lang.Override
      public org.graylog.plugins.netflow.v9.NetFlowV9Journal.RawNetflowV9 getDefaultInstanceForType() {
        return org.graylog.plugins.netflow.v9.NetFlowV9Journal.RawNetflowV9.getDefaultInstance();
      }

      @java.lang.Override
      public org.graylog.plugins.netflow.v9.NetFlowV9Journal.RawNetflowV9 build() {
        org.graylog.plugins.netflow.v9.NetFlowV9Journal.RawNetflowV9 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.graylog.plugins.netflow.v9.NetFlowV9Journal.RawNetflowV9 buildPartial() {
        org.graylog.plugins.netflow.v9.NetFlowV9Journal.RawNetflowV9 result = new org.graylog.plugins.netflow.v9.NetFlowV9Journal.RawNetflowV9(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.graylog.plugins.netflow.v9.NetFlowV9Journal.RawNetflowV9 result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.templates_ = internalGetTemplates();
          result.templates_.makeImmutable();
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.optionTemplate_ = internalGetOptionTemplate();
          result.optionTemplate_.makeImmutable();
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          packets_.makeImmutable();
          result.packets_ = packets_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.graylog.plugins.netflow.v9.NetFlowV9Journal.RawNetflowV9) {
          return mergeFrom((org.graylog.plugins.netflow.v9.NetFlowV9Journal.RawNetflowV9)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.graylog.plugins.netflow.v9.NetFlowV9Journal.RawNetflowV9 other) {
        if (other == org.graylog.plugins.netflow.v9.NetFlowV9Journal.RawNetflowV9.getDefaultInstance()) return this;
        internalGetMutableTemplates().mergeFrom(
            other.internalGetTemplates());
        bitField0_ |= 0x00000001;
        internalGetMutableOptionTemplate().mergeFrom(
            other.internalGetOptionTemplate());
        bitField0_ |= 0x00000002;
        if (!other.packets_.isEmpty()) {
          if (packets_.isEmpty()) {
            packets_ = other.packets_;
            packets_.makeImmutable();
            bitField0_ |= 0x00000004;
          } else {
            ensurePacketsIsMutable();
            packets_.addAll(other.packets_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.google.protobuf.MapEntry<java.lang.Integer, com.google.protobuf.ByteString>
                templates__ = input.readMessage(
                    TemplatesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableTemplates().getMutableMap().put(
                    templates__.getKey(), templates__.getValue());
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                com.google.protobuf.MapEntry<java.lang.Integer, com.google.protobuf.ByteString>
                optionTemplate__ = input.readMessage(
                    OptionTemplateDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableOptionTemplate().getMutableMap().put(
                    optionTemplate__.getKey(), optionTemplate__.getValue());
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                com.google.protobuf.ByteString v = input.readBytes();
                ensurePacketsIsMutable();
                packets_.add(v);
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.Integer, com.google.protobuf.ByteString> templates_;
      private com.google.protobuf.MapField<java.lang.Integer, com.google.protobuf.ByteString>
          internalGetTemplates() {
        if (templates_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              TemplatesDefaultEntryHolder.defaultEntry);
        }
        return templates_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, com.google.protobuf.ByteString>
          internalGetMutableTemplates() {
        if (templates_ == null) {
          templates_ = com.google.protobuf.MapField.newMapField(
              TemplatesDefaultEntryHolder.defaultEntry);
        }
        if (!templates_.isMutable()) {
          templates_ = templates_.copy();
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return templates_;
      }
      public int getTemplatesCount() {
        return internalGetTemplates().getMap().size();
      }
      /**
       * <pre>
       * all applicable templates that are referenced by the packets
       * </pre>
       *
       * <code>map&lt;uint32, bytes&gt; templates = 1;</code>
       */
      @java.lang.Override
      public boolean containsTemplates(
          int key) {

        return internalGetTemplates().getMap().containsKey(key);
      }
      /**
       * Use {@link #getTemplatesMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, com.google.protobuf.ByteString> getTemplates() {
        return getTemplatesMap();
      }
      /**
       * <pre>
       * all applicable templates that are referenced by the packets
       * </pre>
       *
       * <code>map&lt;uint32, bytes&gt; templates = 1;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.Integer, com.google.protobuf.ByteString> getTemplatesMap() {
        return internalGetTemplates().getMap();
      }
      /**
       * <pre>
       * all applicable templates that are referenced by the packets
       * </pre>
       *
       * <code>map&lt;uint32, bytes&gt; templates = 1;</code>
       */
      @java.lang.Override
      public /* nullable */
com.google.protobuf.ByteString getTemplatesOrDefault(
          int key,
          /* nullable */
com.google.protobuf.ByteString defaultValue) {

        java.util.Map<java.lang.Integer, com.google.protobuf.ByteString> map =
            internalGetTemplates().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * all applicable templates that are referenced by the packets
       * </pre>
       *
       * <code>map&lt;uint32, bytes&gt; templates = 1;</code>
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getTemplatesOrThrow(
          int key) {

        java.util.Map<java.lang.Integer, com.google.protobuf.ByteString> map =
            internalGetTemplates().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearTemplates() {
        bitField0_ = (bitField0_ & ~0x00000001);
        internalGetMutableTemplates().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       * all applicable templates that are referenced by the packets
       * </pre>
       *
       * <code>map&lt;uint32, bytes&gt; templates = 1;</code>
       */
      public Builder removeTemplates(
          int key) {

        internalGetMutableTemplates().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, com.google.protobuf.ByteString>
          getMutableTemplates() {
        bitField0_ |= 0x00000001;
        return internalGetMutableTemplates().getMutableMap();
      }
      /**
       * <pre>
       * all applicable templates that are referenced by the packets
       * </pre>
       *
       * <code>map&lt;uint32, bytes&gt; templates = 1;</code>
       */
      public Builder putTemplates(
          int key,
          com.google.protobuf.ByteString value) {

        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableTemplates().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       * all applicable templates that are referenced by the packets
       * </pre>
       *
       * <code>map&lt;uint32, bytes&gt; templates = 1;</code>
       */
      public Builder putAllTemplates(
          java.util.Map<java.lang.Integer, com.google.protobuf.ByteString> values) {
        internalGetMutableTemplates().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000001;
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.Integer, com.google.protobuf.ByteString> optionTemplate_;
      private com.google.protobuf.MapField<java.lang.Integer, com.google.protobuf.ByteString>
          internalGetOptionTemplate() {
        if (optionTemplate_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              OptionTemplateDefaultEntryHolder.defaultEntry);
        }
        return optionTemplate_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, com.google.protobuf.ByteString>
          internalGetMutableOptionTemplate() {
        if (optionTemplate_ == null) {
          optionTemplate_ = com.google.protobuf.MapField.newMapField(
              OptionTemplateDefaultEntryHolder.defaultEntry);
        }
        if (!optionTemplate_.isMutable()) {
          optionTemplate_ = optionTemplate_.copy();
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return optionTemplate_;
      }
      public int getOptionTemplateCount() {
        return internalGetOptionTemplate().getMap().size();
      }
      /**
       * <pre>
       * there is only one option template, but we need to know its template id, so a map is the easiest way to find it
       * </pre>
       *
       * <code>map&lt;uint32, bytes&gt; optionTemplate = 2;</code>
       */
      @java.lang.Override
      public boolean containsOptionTemplate(
          int key) {

        return internalGetOptionTemplate().getMap().containsKey(key);
      }
      /**
       * Use {@link #getOptionTemplateMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, com.google.protobuf.ByteString> getOptionTemplate() {
        return getOptionTemplateMap();
      }
      /**
       * <pre>
       * there is only one option template, but we need to know its template id, so a map is the easiest way to find it
       * </pre>
       *
       * <code>map&lt;uint32, bytes&gt; optionTemplate = 2;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.Integer, com.google.protobuf.ByteString> getOptionTemplateMap() {
        return internalGetOptionTemplate().getMap();
      }
      /**
       * <pre>
       * there is only one option template, but we need to know its template id, so a map is the easiest way to find it
       * </pre>
       *
       * <code>map&lt;uint32, bytes&gt; optionTemplate = 2;</code>
       */
      @java.lang.Override
      public /* nullable */
com.google.protobuf.ByteString getOptionTemplateOrDefault(
          int key,
          /* nullable */
com.google.protobuf.ByteString defaultValue) {

        java.util.Map<java.lang.Integer, com.google.protobuf.ByteString> map =
            internalGetOptionTemplate().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * there is only one option template, but we need to know its template id, so a map is the easiest way to find it
       * </pre>
       *
       * <code>map&lt;uint32, bytes&gt; optionTemplate = 2;</code>
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getOptionTemplateOrThrow(
          int key) {

        java.util.Map<java.lang.Integer, com.google.protobuf.ByteString> map =
            internalGetOptionTemplate().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearOptionTemplate() {
        bitField0_ = (bitField0_ & ~0x00000002);
        internalGetMutableOptionTemplate().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       * there is only one option template, but we need to know its template id, so a map is the easiest way to find it
       * </pre>
       *
       * <code>map&lt;uint32, bytes&gt; optionTemplate = 2;</code>
       */
      public Builder removeOptionTemplate(
          int key) {

        internalGetMutableOptionTemplate().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, com.google.protobuf.ByteString>
          getMutableOptionTemplate() {
        bitField0_ |= 0x00000002;
        return internalGetMutableOptionTemplate().getMutableMap();
      }
      /**
       * <pre>
       * there is only one option template, but we need to know its template id, so a map is the easiest way to find it
       * </pre>
       *
       * <code>map&lt;uint32, bytes&gt; optionTemplate = 2;</code>
       */
      public Builder putOptionTemplate(
          int key,
          com.google.protobuf.ByteString value) {

        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableOptionTemplate().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       * there is only one option template, but we need to know its template id, so a map is the easiest way to find it
       * </pre>
       *
       * <code>map&lt;uint32, bytes&gt; optionTemplate = 2;</code>
       */
      public Builder putAllOptionTemplate(
          java.util.Map<java.lang.Integer, com.google.protobuf.ByteString> values) {
        internalGetMutableOptionTemplate().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000002;
        return this;
      }

      private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> packets_ = emptyList(com.google.protobuf.ByteString.class);
      private void ensurePacketsIsMutable() {
        if (!packets_.isModifiable()) {
          packets_ = makeMutableCopy(packets_);
        }
        bitField0_ |= 0x00000004;
      }
      /**
       * <pre>
       * the raw packets as received. it might contain templates as well, but even if it does the above fields will have that information, too
       * in case we previously buffered flows, this may contain more than one flow. in situations when we have all templates already
       * this will be a single packet sent by the exporter
       * </pre>
       *
       * <code>repeated bytes packets = 3;</code>
       * @return A list containing the packets.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getPacketsList() {
        packets_.makeImmutable();
        return packets_;
      }
      /**
       * <pre>
       * the raw packets as received. it might contain templates as well, but even if it does the above fields will have that information, too
       * in case we previously buffered flows, this may contain more than one flow. in situations when we have all templates already
       * this will be a single packet sent by the exporter
       * </pre>
       *
       * <code>repeated bytes packets = 3;</code>
       * @return The count of packets.
       */
      public int getPacketsCount() {
        return packets_.size();
      }
      /**
       * <pre>
       * the raw packets as received. it might contain templates as well, but even if it does the above fields will have that information, too
       * in case we previously buffered flows, this may contain more than one flow. in situations when we have all templates already
       * this will be a single packet sent by the exporter
       * </pre>
       *
       * <code>repeated bytes packets = 3;</code>
       * @param index The index of the element to return.
       * @return The packets at the given index.
       */
      public com.google.protobuf.ByteString getPackets(int index) {
        return packets_.get(index);
      }
      /**
       * <pre>
       * the raw packets as received. it might contain templates as well, but even if it does the above fields will have that information, too
       * in case we previously buffered flows, this may contain more than one flow. in situations when we have all templates already
       * this will be a single packet sent by the exporter
       * </pre>
       *
       * <code>repeated bytes packets = 3;</code>
       * @param index The index to set the value at.
       * @param value The packets to set.
       * @return This builder for chaining.
       */
      public Builder setPackets(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        ensurePacketsIsMutable();
        packets_.set(index, value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the raw packets as received. it might contain templates as well, but even if it does the above fields will have that information, too
       * in case we previously buffered flows, this may contain more than one flow. in situations when we have all templates already
       * this will be a single packet sent by the exporter
       * </pre>
       *
       * <code>repeated bytes packets = 3;</code>
       * @param value The packets to add.
       * @return This builder for chaining.
       */
      public Builder addPackets(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        ensurePacketsIsMutable();
        packets_.add(value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the raw packets as received. it might contain templates as well, but even if it does the above fields will have that information, too
       * in case we previously buffered flows, this may contain more than one flow. in situations when we have all templates already
       * this will be a single packet sent by the exporter
       * </pre>
       *
       * <code>repeated bytes packets = 3;</code>
       * @param values The packets to add.
       * @return This builder for chaining.
       */
      public Builder addAllPackets(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensurePacketsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, packets_);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the raw packets as received. it might contain templates as well, but even if it does the above fields will have that information, too
       * in case we previously buffered flows, this may contain more than one flow. in situations when we have all templates already
       * this will be a single packet sent by the exporter
       * </pre>
       *
       * <code>repeated bytes packets = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPackets() {
        packets_ = emptyList(com.google.protobuf.ByteString.class);
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.graylog.plugins.netflow.v9.RawNetflowV9)
    }

    // @@protoc_insertion_point(class_scope:org.graylog.plugins.netflow.v9.RawNetflowV9)
    private static final org.graylog.plugins.netflow.v9.NetFlowV9Journal.RawNetflowV9 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.graylog.plugins.netflow.v9.NetFlowV9Journal.RawNetflowV9();
    }

    public static org.graylog.plugins.netflow.v9.NetFlowV9Journal.RawNetflowV9 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RawNetflowV9>
        PARSER = new com.google.protobuf.AbstractParser<RawNetflowV9>() {
      @java.lang.Override
      public RawNetflowV9 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RawNetflowV9> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RawNetflowV9> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.graylog.plugins.netflow.v9.NetFlowV9Journal.RawNetflowV9 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_graylog_plugins_netflow_v9_RawNetflowV9_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_graylog_plugins_netflow_v9_RawNetflowV9_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_graylog_plugins_netflow_v9_RawNetflowV9_TemplatesEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_graylog_plugins_netflow_v9_RawNetflowV9_TemplatesEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_graylog_plugins_netflow_v9_RawNetflowV9_OptionTemplateEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_graylog_plugins_netflow_v9_RawNetflowV9_OptionTemplateEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#src/main/resources/netflow_v9.proto\022\036o" +
      "rg.graylog.plugins.netflow.v9\"\262\002\n\014RawNet" +
      "flowV9\022N\n\ttemplates\030\001 \003(\0132;.org.graylog." +
      "plugins.netflow.v9.RawNetflowV9.Template" +
      "sEntry\022X\n\016optionTemplate\030\002 \003(\0132@.org.gra" +
      "ylog.plugins.netflow.v9.RawNetflowV9.Opt" +
      "ionTemplateEntry\022\017\n\007packets\030\003 \003(\014\0320\n\016Tem" +
      "platesEntry\022\013\n\003key\030\001 \001(\r\022\r\n\005value\030\002 \001(\014:" +
      "\0028\001\0325\n\023OptionTemplateEntry\022\013\n\003key\030\001 \001(\r\022" +
      "\r\n\005value\030\002 \001(\014:\0028\001B2\n\036org.graylog.plugin" +
      "s.netflow.v9B\020NetFlowV9Journal"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_graylog_plugins_netflow_v9_RawNetflowV9_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_graylog_plugins_netflow_v9_RawNetflowV9_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_graylog_plugins_netflow_v9_RawNetflowV9_descriptor,
        new java.lang.String[] { "Templates", "OptionTemplate", "Packets", });
    internal_static_org_graylog_plugins_netflow_v9_RawNetflowV9_TemplatesEntry_descriptor =
      internal_static_org_graylog_plugins_netflow_v9_RawNetflowV9_descriptor.getNestedTypes().get(0);
    internal_static_org_graylog_plugins_netflow_v9_RawNetflowV9_TemplatesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_graylog_plugins_netflow_v9_RawNetflowV9_TemplatesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_org_graylog_plugins_netflow_v9_RawNetflowV9_OptionTemplateEntry_descriptor =
      internal_static_org_graylog_plugins_netflow_v9_RawNetflowV9_descriptor.getNestedTypes().get(1);
    internal_static_org_graylog_plugins_netflow_v9_RawNetflowV9_OptionTemplateEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_graylog_plugins_netflow_v9_RawNetflowV9_OptionTemplateEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
