---
##
 # Copyright OpenSearch Contributors
 # SPDX-License-Identifier: Apache-2.0
##

# configuration file for the notifications-core plugin
opensearch.notifications.core:
  email:
    size_limit: 10000
    minimum_header_length: 100
  http:
    max_connections: 60
    max_connection_per_route: 20
    connection_timeout: 5000 # in milliseconds
    socket_timeout: 50000
    host_deny_list: []
  allowed_config_types: ["slack","chime","webhook","email","sns","ses_account","smtp_account","email_group"]
  tooltip_support: true
