type = "changed"
message = "Automatically choose default number of process-buffer and output-buffer processors based on available CPU cores."

issues = ["17450"]
pulls = ["17737"]

details.user = """
The default values for the configuration settings `processbuffer_processors` and `outputbuffer_processors` have been
changed. The values will now be calculated based on the number of CPU cores available to the JVM. If you have not
explicitly set values for these settings in your configuration file, the new defaults apply.

The new defaults should improve performance of your system, however, if you want to continue running your system with
the previous defaults, please add the following settings to your configuration file:

```
processbuffer_processors = 5
outputbuffer_processors = 3
```
"""
