version: "3.9"
services:
  datanode:
    build: .
    ports:
      - "8999:8999"
      - "9200:9200"
    depends_on:
      mongodb:
        condition: "service_started"
  mongodb:
    image: "mongo:5.0"
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
