on: issue_comment
name: Automatic Rebase
jobs:
  rebase:
    name: Rebase
    if: github.event.issue.pull_request != '' && github.event.comment.body == '/rebase'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Automatic Rebase
      uses: Graylog2/rebase@1.3.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

