name: PR Review

on:
  pull_request:
    paths:
      - '**.[jt]sx?'
    types:
      - opened
      - edited
      - synchronize

jobs:
  linter:
    name: Reviewbot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin
          cache: maven
      - uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Compile with Maven / Install dependencies
        run: ./mvnw --fail-fast -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3 -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.test.skip -Dskip.datanode -Dcyclonedx.skip compile
      - name: Reviewbot
        uses: Graylog2/reviewbot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prefix: graylog2-web-interface
