name: Updating yarn lockfile

on:
  schedule:
    - cron: '0 */12 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: graylog2-web-interface

    steps:
      - uses: actions/checkout@v2
      - name: Set up Yarn cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-yarn-${{ hashFiles('graylog2-web-interface/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
          path: ~/.cache/yarn
      - name: Install dependencies
        run: yarn install
      - name: Create/Update Pull Request
        uses: Graylog2/create-pull-request@7380612b49221684fefa025244f2ef4008ae50ad
        with:
          title: Updating yarn lockfile
          body: This PR was created by a job that is running periodically to update the yarn lockfile after transitive dependencies have been updated.
          author: Gary Bot <garybot2@graylog.com>
          branch: update-yarn-lockfile
          committer: Gary Bot <garybot2@graylog.com>
          commit-message: Updating yarn lockfile
          delete-branch: true
