type = "a"
message = "Lookup table page UI revamp"

<<<<<<< HEAD
issues = ["Graylog2/graylog-plugin-enterprise#11108", "Graylog2/graylog-plugin-enterprise#11107", "Graylog2/graylog-plugin-enterprise#11115"]
pulls = ["23056"]
=======
issues = ["Graylog2/graylog-plugin-enterprise#11108"]
pulls = ["23056", "23203"]
>>>>>>> 9fb7c4a4c7cc6b444f9425afdda493d48596ec73
