type = "c"
message = "Pipeline rule builder displays an error message if a variable name is a reserved keyword."
details.user = """
The rule language includes a number of reserved keywords, e.g. `let`, `and`, `then`, etc.
Variable names may not match any of these keywords.
"""

issues = ["7006"]
pulls = ["17680"]
