type = "f" # One of: a(dded), c(hanged), d(eprecated), r(emoved), f(ixed), s(ecurity)
message = "Fixes validation of max index retention lifetime for time-size-optimizing indices."

issues = ["Graylog2/graylog-plugin-enterprise#5685"]
pulls = ["16392"]
