type = "fixed"
message = "Fix NodeService#allActive() implementation, returning only nodes of correct type"

pulls = []

details.user = """
With the addition of the DATANODE type to the NodeService, the allActive method would return also datanodes. This
may lead to problems in calls that expect only SERVER type.
"""
