type = "a"
message = """
Adds a unique `username` index to the `user` collection to prevent creation of duplicate users.
Any existing duplicates are resolved by appending the user ID.
"""
issues = ["12963"]
pulls = ["14649"]
