# Entry type according to https://keepachangelog.com/en/1.0.0/
# One of: a(dded), c(hanged), d(eprecated), r(emoved), f(ixed), s(ecurity)
type = "fixed"
message = "Pipeline function flatten_json respects the original JSON types"

issues = ["13888"]
pulls = ["13947"]
