type = "a"
message = "Add support for configuring Index Set Defaults"

issues = ["graylog-plugin-enterprise#3264", "graylog-plugin-enterprise#3319"]
pulls = ["13018"]

contributors = [""]

details.user = """
"""

details.ops = """
Detail API changes here.
"""
