type = "a" # One of: a(dded), c(hanged), d(eprecated), r(emoved), f(ixed), s(ecurity)
message = "Adds permissions to restrict input types."

issues = ["graylog-plugin-enterprise#10477"]
pulls = ["22468"]
